### ISSUE TITLE
We will change the `safeParse` API of Valibot

### ISSUE THREAD

**Issue by fabian-hiller** [honojs/middleware#110]
This is just a hint that we will change the `safeParse` API. `.error` will be deprecated and `.issues` will be added.

- https://github.com/fabian-hiller/valibot/blob/main/library/src/methods/safeParse/safeParse.ts
- https://github.com/honojs/middleware/blob/main/packages/valibot-validator/src/index.ts#L29

**Comment by yusukebe** [comment]
@fabian-hiller 

In our `valibot` middleware, we didn't directly use `.error`. Therefore, it's not a breaking issue. Thanks!

**Comment by ZerNico** [comment]
@yusukebe the typings for the hook are gonna change, though.

Hey @fabian-hiller could we maybe export the return type of safeParse for this?

I could also just infer it with `ReturnType<typeof safeParse<T>>` but having it exported probably is the nicer way.

**Comment by yusukebe** [comment]
@ZerNico 

> the typings for the hook are gonna change, though.

Ah, you right. Sorry!

**Comment by fabian-hiller** [comment]
> Hey @fabian-hiller could we maybe export the return type of safeParse for this?

Yes, good idea! https://github.com/fabian-hiller/valibot/blob/main/library/src/methods/safeParse/types.ts

**Comment by ZerNico** [comment]
Awesome, thank you!

I'll update the middleware after the next Valibot version is published then.

**Comment by fabian-hiller** [comment]
I'll write you here as soon as the version is available.

**Comment by yusukebe** [comment]
@fabian-hiller 

Thanks!

**Comment by fabian-hiller** [comment]
The new version v0.13.0 is available.

**Comment by ZerNico** [comment]
Mhh the updated object validation does not work with the hono validator for some reason. The constructor does not equal `Object` even though it is an object.

**Comment by fabian-hiller** [comment]
This is strange. Is it only in development mode or also in production? If we don't find a quick fix, I can change the validation back to the previous if statement.

**Comment by fabian-hiller** [comment]
I changed it back to the typeof operator in v0.13.1

**Comment by ZerNico** [comment]
Did happen in both, seems really weird, I have no idea what causes this. Is the typeof check worse in some way?
I can investigate some more when I have more time.

**Comment by fabian-hiller** [comment]
`typeof` is a bit less accurate because all objects are allowed. However, in practice this is mostly irrelevant.
