### ISSUE TITLE
Sentry middleware: pass env vars as headers

### ISSUE THREAD

**Issue by geelen** [honojs/middleware#113]
I'm trying to port some code that currently uses Toucan directly to use `@hono/sentry`

```js
    const sentry = new Toucan({
      dsn: env.SENTRY_DSN,
      request: c.req.raw,
      transportOptions: {
        headers: {
          "X-Client-ID": env.SENTRY_CLIENT_ID,
          "X-Client-Secret": env.SENTRY_CLIENT_SECRET,
        },
      },
      environment: env.ENV,
    });
```

But I don't have a way to reference env vars in the `@hono/sentry` constructor as it stands, I had to do this:

```js
app.use("*", (c, next) =>
  sentry(
    {
      transportOptions: {
        headers: {
          "X-Client-ID": c.env.SENTRY_CLIENT_ID,
          "X-Client-Secret": c.env.SENTRY_CLIENT_SECRET,
        },
      },
      environment: c.env.ENV,
    },
  )(c, next),
);
```

Which works, but isn't great. Also `transportOptions` wasn't one of the headers in the types, but thankfully they still got passed through: https://github.com/honojs/middleware/blob/main/packages/sentry/src/index.ts#L49

Thoughts?

**Comment by yusukebe** [comment]
Hi @geelen,

> Which works, but isn't great.

You're right; it might not be the most elegant solution. But, this method is the only way we currently handle environment values, and we have recommended it on our website. For example, users can implement basic authentication middleware as shown:

```ts
app.use('/auth/*', async (c, next) => {
  const auth = basicAuth({
    username: c.env.USERNAME,
    password: c.env.PASSWORD,
  })
  return auth(c, next)
})
```

Hmm. To be honest, I'm struggling to find a more good solution. But, I think our current approach keeps the middleware implementation simple.

**Comment by yusukebe** [comment]
@geelen 

> Also `transportOptions` wasn't one of the headers in the types, but thankfully they still got passed through: https://github.com/honojs/middleware/blob/main/packages/sentry/src/index.ts#L49

This is fixed in #130

**Comment by rafaell-lycan** [comment]
@yusukebe should this issue be closed or converted to a discussion?

**Comment by yusukebe** [comment]
@rafaell-lycan Thanks.

Closing this issue.
