### ISSUE TITLE
Router Type Error when using the zValidator

### ISSUE THREAD

**Issue by JacobMGEvans** [honojs/middleware#143]
When using the `new Hono` context generic, and the `zValidator` the types dont overlap, the validator seems to lack the context type or able to somehow use it as a generic.

```ts
export const archiveRouter = new Hono<{ Bindings: Env }>();

const paramValidator = zValidator('param', z.object({ archiveID: z.string() }));

archiveRouter.put('/:archiveID', paramValidator, teamQueryValidator, async (c) => { ... } 

```

The TS Error: 
```bash
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'MiddlewareHandler<Env, string, { in: { param: { archiveID: string; }; }; out: { param: { archiveID: string; }; }; }>'
 is not assignable to parameter of type 'H<{ Bindings: Env; }, string, { in: { param: { archiveID: string; }; }; out: { param: { archiveID: string; }; }; }, {}>'.ts(2769)
```

Temporary solution: 
//@ ts-ignore - The Validator middleware internal types clash with the Router types MiddlewareHandler<Env> -> { Bindings: Env }

**Comment by yusukebe** [comment]
Hi @JacobMGEvans

TypeScript can sometimes be a bit tricky. To get the correct type inference, you can try writing it like this:

```ts
export const archiveRouter = new Hono<{ Bindings: Env }>();

const paramSchema = z.object({ archiveID: z.string() })

archiveRouter.put('/:archiveID', zValidator('param', paramSchema), async (c) => { ... } )
```

Give it a shot and let me know if it work or not.

**Comment by JacobMGEvans** [comment]
Yeah that worked, definitely strange but appreciate the help 😄

**Comment by JacobMGEvans** [comment]
Getting the same Type error again but this time it is the same pattern you suggested that was previously working. 

Not sure if this is related but I saw that the CI tests for [`Zvalidator` ](https://github.com/honojs/middleware/actions/runs/5960454187/job/16167796079)

<img width="557" alt="Screenshot 2023-08-31 at 3 51 59 PM" src="https://github.com/honojs/middleware/assets/27247160/129b4b93-8bf1-4dbb-9b1a-79be7019506d">

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'MiddlewareHandler<Env, string, { in: { json: { expireInHours?: number | undefined; }; }; out: { json: { expireInHours?: number | undefined; }; }; }>' is not assignable to parameter of type 'H<{ Bindings: Env; }, "/artifacts/manual-cache-bust", {}, HandlerResponse<any>>'.
      Type 'MiddlewareHandler<Env, string, { in: { json: { expireInHours?: number | undefined; }; }; out: { json: { expireInHours?: number | undefined; }; }; }>' is not assignable to type 'MiddlewareHandler<{ Bindings: Env; }, "/artifacts/manual-cache-bust", {}>'.
        Types of parameters 'c' and 'c' are incompatible.
          Property '_path' is missing in type 'Context<{ Bindings: Env; }, "/artifacts/manual-cache-bust", {}>' but required in type 'Context<Env, string, { in: { json: { expireInHours?: number | undefined; }; }; out: { json: { expireInHours?: number | undefined; }; }; }>'.ts(2769)
```

**Comment by yusukebe** [comment]
Hi @JacobMGEvans and @mrbbot,

I'm just thinking about this issue. Yeah – if the **file path** referenced in `hono` differs from that in `@hono/zod-validator`, it could cause the type errors, even if the type structures are identical. I discussed a same issue with @geelen a few days ago. TypeScript is tricky:(

Anyway, thanks!
