### ISSUE TITLE
issue with Path Parameter Definition in Swagger using @hono/zod-openapi

### ISSUE THREAD

**Issue by omar-tekab** [honojs/middleware#144]
# Issue Description:

![unnamed](https://github.com/honojs/middleware/assets/117732586/1710db99-2c7d-4a43-8ea3-30c86cb7755a)

When following the example provided by @hono/zod-openapi and using the path parameter syntax '{id}' in Swagger to define an endpoint path like '/users/{id}', an issue arises where the defined endpoint cannot be found. This results in a 404 error when testing the endpoint with Postman or any. However, when the path is manually changed to '/users/:id', the endpoint functions correctly.

# Steps to Reproduce:

Utilize the example provided by @hono/zod-openapi for defining an endpoint path with a path parameter using '{id}' syntax.
Try to access the defined endpoint using Postman or any other API testing tool.

# Expected Behavior:
The endpoint defined with the '{id}' syntax should be successfully recognized and accessible both in Swagger documentation and when tested.

# Actual Behavior:
When using the defined '{id}' path parameter syntax in Swagger, the endpoint cannot be found, and a 404 error is returned when testing the endpoint api call. However, changing the path parameter syntax to '/users/:id' makes the endpoint work as expected.

# Additional Information:

This issue seems to be specific to the use of the '{id}' path parameter syntax in Swagger, as manually changing it to '/users/:id' in both the Swagger documentation and the testing tool resolves the issue.
When modifying the OpenAPI documentation directly to use '/users/{id}' and accessing the endpoint, it functions correctly.
It appears that the inconsistency lies in how the '{id}' syntax is interpreted when used within the Swagger documentation.

# Environment Details:

Library: @hono/zod-openapi
OpenAPI Definition: (Provide the relevant OpenAPI definition excerpt where the endpoint is defined)
Testing Tool: Postman (or specify the testing tool used)
API Endpoint Path: '/users/{id}'
HTTP Method: GET (or specify the method)

## Screenshots when i use :id in postman and swagger  

![Screenshot from 2023-08-25 14-30-29](https://github.com/honojs/middleware/assets/117732586/60d10d31-97c9-4856-821a-9138a04ab016)

![Screenshot from 2023-08-25 14-32-52](https://github.com/honojs/middleware/assets/117732586/17766d93-d02f-40c1-97ac-90dae45b9ef8)

## Screenshots when i use {id} in postman and swagger 

![Screenshot from 2023-08-25 14-32-11](https://github.com/honojs/middleware/assets/117732586/092b4f4b-748c-48bb-8139-cef5b344ab89)

![Screenshot from 2023-08-25 14-34-48](https://github.com/honojs/middleware/assets/117732586/e137d746-f4d1-4162-9b0e-26ff0093f7a4)

# Labels:

Bug
Swagger
OpenAPI
Path Parameter
Your prompt attention to this issue would be greatly appreciated. If additional information is required, please let me know. Thank you for your assistance in resolving this matter.

**Comment by yusukebe** [comment]
Hi @omar-tekab 

this but is moving be fix in latest version. Could you try with it?

**Comment by omar-tekab** [comment]
Thank you! The bug has been fixed.

**Comment by yusukebe** [comment]
Yeah! Closing the issue.
