### ISSUE TITLE
raise error instead of reponse null and 400 (firebase auth)

### ISSUE THREAD

**Issue by shriharip** [honojs/middleware#185]
Hi,
I was trying to make this work with deno runtime, but I guess might be an issue across all edge networks.

We need to set the middleware for all routes. Reason, on my home page if the user is signed in , (already has a valid authorization) then I need to show Logout Button. 

```
// set middleware
app.use('*', verifyFirebaseAuth(config))
```

Now, let say my root route.
```
app.get('/', (c) => {
 return c.text('Hello from home')
})
````

because the middle ware is called on each route invocation and we try to 

```
 const authorization = c.req.headers.get(config.AuthorizationHeaderKey) 
```

if the authorization is null, we are sending null response with 400. This results in home page also not being shown. So I think, this behavior is not proper or I might be missing something.

**Comment by yusukebe** [comment]
Hi @shriharip 

Middleware such as Basic and Bearer authentication will throw an `HTTPException` when authentication fails.

https://hono.dev/api/exception#throw-httpexception

But, this Firebase Auth middleware only returns a 400 response. If Firebase Auth would throw `HTTPException`, would that solve your problem?

**Comment by shriharip** [comment]
Hello @yusukebe ,

Thanks for your reply and the wonderful honojs . 
I agree that on auth having ```HTTPException``` is valid. However, in my case, I want to show my homepage on my ```/``` index route with some static images and static content. But since the middleware sends a response it is difficult to catch that. 

Yes, having this throw a ```HTTPException``` would be best solution for all those use cases and for me. Thanks.

**Comment by yusukebe** [comment]
@shriharip Okay!

@Code-Hex :

Since [this PR](https://github.com/honojs/hono/pull/796) merged, Basic and Bearer authentication throws [`HTTPException`](https://hono.dev/api/exception#throw-httpexception) when authentication fails. So, can you please make Firebase Auth also throw `HTTPException` with reference to [Basic Auth middleware](https://github.com/honojs/middleware/blob/main/packages/firebase-auth/src/index.ts)?

**Comment by Code-Hex** [comment]
@yusukebe @shriharip I created PR for this: https://github.com/honojs/middleware/pull/191

**Comment by yusukebe** [comment]
This may be fixed by #191. 

@shriharip can you check it out?

**Comment by shriharip** [comment]
Hello @yusukebe , thanks for the fix. 
However, this is still not working as at one place we still need to raise an error.

https://github.com/honojs/middleware/blob/4eb3eb5e5a030d83c537ef6ebd5a80905f6738b5/packages/firebase-auth/src/index.ts#L41C5-L45C6

in this place
````
 if (authorization === null) {
      return new Response(null, {
        status: 400,
      })
    }
````
This should also be 
````
if (authorization === null){
const res = new Response('Unauthorized', {
        status: 401,
      })
      throw new HTTPException(401, { res })
}

`````
I hope you agree too.

**Comment by Code-Hex** [comment]
@shriharip @yusukebe I created PR to fix that 🙏

**Comment by yusukebe** [comment]
We can close this issue! If you have any problem, feel free to reopen.
