### ISSUE TITLE
Surface zValidator errors

### ISSUE THREAD

**Issue by jylin** [honojs/middleware#225]
Is there a way to surface the validation errors somewhere? Seems like the server just returns a 400 error when validation fails without additional information.

**Comment by yusukebe** [comment]
Hi @jylin 

You can use a `hook`:

```ts
app.post(
  '/post',
  zValidator('json', schema, (result, c) => {
    if (!result.success) {
      return c.text('Invalid!', 400)
    }
  })
  //...
)
```

**Comment by jylin** [comment]
Oh I see, thanks!

**Comment by yusukebe** [comment]
@jylin 

Okay. Is this resolved?
