### ISSUE TITLE
@hono/zod-openapi loses context with transform

### ISSUE THREAD

**Issue by treboryx** [honojs/middleware#239]
I have the following schema:

```ts
import { z } from "@hono/zod-openapi";
import { mapKeys, camel } from "radash";

const bodySchema = z
    .record(z.string())
    .transform((x) => mapKeys(x, camel))
    .pipe(
        z.strictObject({
            fieldId: z.string().nullish().openapi({
                description: "Test Field ID",
            }),
            errorType: z.string().openapi({
                description: "Error Type",
            }),
        })
    ) as unknown as AnyZodObject;
```
    
  which constructs the following openapi schema in the spec incorrectly:
  
```json
{
  "requestBody": {
    "content": {
      "application/json": {
        "schema": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

Which is clearly wrong and I assume loses the context when using transform. This validator actually works if you run it and is used to accept both snake_case & camelCase and transform the keys into camelCase for validation

Without the transform it will construct the correct openapi schema in the spec:

```ts
const bodySchema = z.strictObject({
    fieldId: z.string().nullish().openapi({
        description: "Test Field ID",
    }),
    errorType: z.string().openapi({
        description: "Error Type",
    }),
});
```

output:

```json
{
  "requestBody": {
    "content": {
      "application/json": {
        "schema": {
          "type": "object",
          "properties": {
            "fieldId": {
              "type": "string",
              "nullable": true,
              "description": "Test Field ID"
            },
            "errorType": {
              "type": "string",
              "description": "Error Type"
            }
          },
          "required": ["errorType"],
          "additionalProperties": false
        }
      }
    }
  }
}
```

So I'm assuming the context of the actual object is lost when using transform or something related to that.

**Comment by yusukebe** [comment]
Hi @treboryx .

This issue isn't related to Hono; it concerns the [Zod to OpenAPI](https://github.com/asteasolutions/zod-to-openapi) library which is used in the middleware. You can reproduce it with the following code:

```ts
import { OpenAPIRegistry, OpenApiGeneratorV3, extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi'
import { AnyZodObject, z } from 'zod'
import { mapKeys, camel } from 'radash'

extendZodWithOpenApi(z)

const registry = new OpenAPIRegistry()

const bodySchema = z
  .record(z.string())
  .transform((x) => mapKeys(x, camel))
  .pipe(
    z.strictObject({
      fieldId: z.string().nullish().openapi({
        description: 'Test Field ID'
      }),
      errorType: z.string().openapi({
        description: 'Error Type'
      })
    })
  ) as unknown as AnyZodObject

registry.register('body', bodySchema)
const generator = new OpenApiGeneratorV3(registry.definitions)
const component = generator.generateComponents()

console.log(JSON.stringify(component, null, 2))
```

**Comment by treboryx** [comment]
> Hi @treboryx .
> 
> This issue isn't related to Hono; it concerns the [Zod to OpenAPI](https://github.com/asteasolutions/zod-to-openapi) library which is used in the middleware. You can reproduce it with the following code:
> 
> ```ts
> import { OpenAPIRegistry, OpenApiGeneratorV3, extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi'
> import { AnyZodObject, z } from 'zod'
> import { mapKeys, camel } from 'radash'
> 
> extendZodWithOpenApi(z)
> 
> const registry = new OpenAPIRegistry()
> 
> const bodySchema = z
>   .record(z.string())
>   .transform((x) => mapKeys(x, camel))
>   .pipe(
>     z.strictObject({
>       fieldId: z.string().nullish().openapi({
>         description: 'Test Field ID'
>       }),
>       errorType: z.string().openapi({
>         description: 'Error Type'
>       })
>     })
>   ) as unknown as AnyZodObject
> 
> registry.register('body', bodySchema)
> const generator = new OpenApiGeneratorV3(registry.definitions)
> const component = generator.generateComponents()
> 
> console.log(JSON.stringify(component, null, 2))
> ```

Thank you! :)
