### ISSUE TITLE
[feature request] Uploads middleware

### ISSUE THREAD

**Issue by silvioprog** [honojs/middleware#26]
Hi.

It would be nice to make it easy to handle uploads.

References:

- https://github.com/denoland/deploy_feedback/issues/328
- https://expressjs.com/en/resources/middleware/multer.html
- https://github.com/richardgirges/express-fileupload

**Comment by yusukebe** [comment]
Hi @silvioprog !

That is a good idea, and if we'll make one, it might be Built-in Middleware. So, let's close this Issue and re-open the Issue in the core repository.
