### ISSUE TITLE
@hono/oauth-providers npm package is missing transpiled code

### ISSUE THREAD

**Issue by Jastor11** [honojs/middleware#275]
There is no code available in the current version of the published NPM package

![Screenshot 2023-11-27 at 1 45 51 PM](https://github.com/honojs/middleware/assets/11326581/1fc28fd1-61cb-44ed-a91d-7445db9b2fbd)

**Comment by yusukebe** [comment]
@Jastor11 

Sorry! Fixed and shipped it.

**Comment by Jastor11** [comment]
Thank you!
