### ISSUE TITLE
Want to use predefined components in OpenAPI, but when using references, type inference is not possible.

### ISSUE THREAD

**Issue by sonodar** [honojs/middleware#282]
OpenAPI の schemas ref を利用したいのですが、それをやるとルートハンドラーで型推論ができません。

```ts
import { OpenAPIHono, createRoute, z } from "@hono/zod-openapi";

const app = new OpenAPIHono();

const loginRequest = z.object({
  username: z.string(),
  password: z.string(),
});
app.openAPIRegistry.register("LoginRequest", loginRequest);

const loginResponse = z.object({
  sessionId: z.string(),
});
app.openAPIRegistry.register("LoginResponse", loginResponse);

app.openapi(
  createRoute({
    method: "post",
    path: "/login",
    request: {
      body: {
        required: true,
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/LoginRequest" },
          },
        },
      },
    },
    responses: {
      200: {
        description: "OK",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/LoginResponse" },
          },
        },
      },
    },
  }),
  (c) => {
    const { username, password } = c.req.valid("json"); // error TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.
    return c.jsonT({ sessionId: username });
  }
);

app.get("/", (c) => c.text("Hello Hono!"));

export default app;
```

* hono@3.10.2
* @hono/zod-openapi@0.9.0

**Comment by yusukebe** [comment]
Hi @sonodar,

This feature is currently not supported. Implementing it will be challenging, so I'm not sure if we can make it at the moment.

@sor4chi,

If you're interested, could you look into it?

**Comment by sor4chi** [comment]
@yusukebe 
It would certainly be useful and doable, but it would be an extension of zod-openapi.
I don't think this is something that hono zod openapi should do, but rather a responsibility of zod openapi, what do you think?

**Comment by yusukebe** [comment]
@sor4chi

Thank you! We don't need to do that. Additionally, could you investigate whether the validation in `Zod OpenAPI Hono` actually works when using `schemas ref`? I suspect it might not.

**Comment by sor4chi** [comment]
Okay,I'll see it tomorrow:)

**Comment by sor4chi** [comment]
@yusukebe
Didn't work.
In the above code, the request passes through to the handler without any validation.

**Comment by sor4chi** [comment]
@sonodar
This is just a question, but is there any reason to use 

```ts
const loginRequest = z.object({
  username: z.string(),
  password: z.string(),
});

// ...

"application/json": {
  schema: loginRequest,
},
```

instead of 

```ts
const loginRequest = z.object({
  username: z.string(),
  password: z.string(),
});
app.openAPIRegistry.register("LoginRequest", loginRequest);

// ...

"application/json": {
  schema: { $ref: "#/components/schemas/LoginRequest" },
},
```

as recommended by zod-openapi?
Is it for the Swagger UI?

**Comment by sonodar** [comment]
@sor4chi 

ご対応ありがとうございます。すみません、英語での説明が難しいので日本語で失礼します。

直近で問題視しているのは、私が利用している Zodios コードを生成する `openapi-zod-client` では匿名コンポーネントのレスポンスはモデルのソースコードが生成されません。厳密には生成されてはいるけど export されないため使い勝手が悪いです。

ただこれは `openapi-zod-client` 側の問題もありますし、ニッチな要件なので無視するとして。

個人的に考える一般的な課題としては、リクエストボディやレスポンスが *匿名コンポーネント* になることです。
匿名コンポーネントの扱いは Generator によってまちまちです。

例えば openapi-generator では `/login` の `post` リクエストは `LoginPostRequest` というモデルとして、レスポンスは `LoginPost200Response` という命名で生成されます。

同じ構造を表すモデルで、なんなら同じ意味を持つコンポーネントなのに別の名前で出力されるのは直感的でないのと、Java みたいな Structured Type ではない言語では同じ意味のコンポーネントなのに DTO によるデータの授受が発生します。

**Comment by sor4chi** [comment]
@sonodar 

ありがとうございます、日本語承知しました。
`zod-openapi`では`z`のメソッドチェーンに`.openapi()`が拡張されているため、

```ts
const loginRequest = z
  .object({
    username: z.string(),
    password: z.string(),
  })
  .openapi("Hoge");
```

のようにすることでこのSchemaを`#/components/schemas/Hoge`として固定してschemaに登録できるようです。すでに試されていたら申し訳ないのですが、一度確認していただけないでしょうか？

**Comment by sonodar** [comment]
@sor4chi 

こちら試したところほぼ期待した通りの挙動になりました！ありがとうございます！！

**Comment by sor4chi** [comment]
よかったです！！

**Comment by rafaell-lycan** [comment]
Hi @sor4chi @yusukebe 

I came across this issue as I've faced a similar problem and it turns out that we could have a compilation of this base knowledge and add it as either guides or FAQs on the package docs or even (in the future) on Hono's website.

WDYT?

**Comment by yusukebe** [comment]
> I came across this issue as I've faced a similar problem and it turns out that we could have a compilation of this base knowledge and add it as either guides or FAQs on the package docs or even (in the future) on Hono's website.

Okay!

@sor4chi 

Could you write the document for our website about this issue?

**Comment by sor4chi** [comment]
@rafaell-lycan How about this?
https://github.com/honojs/middleware/pull/294

**Comment by rafaell-lycan** [comment]
@sor4chi 👌

**Comment by yusukebe** [comment]
This issue seems to be fixed. Thanks.
