### ISSUE TITLE
[@hono/zod-openapi] Error with testing

### ISSUE THREAD

**Issue by nicobytes** [honojs/middleware#284]
Hi, I'm having problems with testing in Hono. For example, when using a simple Hono app with esbuild-jest it works fine.

![image](https://github.com/honojs/middleware/assets/7611944/75d7cf34-0819-4312-b5b7-c430451a3dfd)

But when I use OpenAPIHono, the unit tests don't work. I tried other configurations, like ts-jest, type="module", but it still doesn't work. Does anyone have any suggestions? 

![a](https://github.com/honojs/middleware/assets/7611944/4a881090-3d3b-4f18-be99-487613bc3828)

Is there an example with testing + zod-openapi?

Here my repo: https://github.com/nicobytes/ai-api

**Comment by monoald** [comment]
Hi @nicobytes!

To fix this you need to config **babel**

- Install babel:

```
npm install --save-dev @babel/core @babel/node @babel/preset-env
```

- Add the config on `babel.config.js`:
```
module.exports = {
  presets: ["@babel/preset-env"]
};
```

- Add the new transform pattern to `jest.config.js`:
```
{
    ...
    transform: {
        '^.+\\.(ts|tsx)$': 'esbuild-jest',
        '^.+\\.js$': 'babel-jest',
    },
}
```
- Then add in ignore patterns the package that is causing the error, (also in `jest.config.js`): 
```
{
    ...
    transformIgnorePatterns: [ "node_modules/(?!(yaml/browser))" ],
}
```

This is the only workaround I found that works

![Screenshot from 2023-12-01 15-29-18](https://github.com/honojs/middleware/assets/67347256/a7f9492a-3153-4d3c-8de0-23b228b570e8)

**Comment by nicobytes** [comment]
Hi! @monoald!

Thanks for your reply and yes, the key is :

```
{
    ...
    transformIgnorePatterns: [ "node_modules/(?!(yaml/browser))" ],
}
```

Because I tried the same configuration but without that last part and on the other hand I tried with vitest and it just works!

**Comment by monoald** [comment]
Glad to hear that! Love the work you do at Platzi btw
