### ISSUE TITLE
Can't get Bearer Auth to work on Swagger UI at all

### ISSUE THREAD

**Issue by bramses** [honojs/middleware#297]
When curling the authed endpoint works great:

```
curl -H "Authorization: Bearer honoiscool" http://localhost:8787/api/page
{"message":"hello, the time is: 2023-12-09T19:14:04.068Z"}%     
```

However in Swagger, I'm getting nothing helpful. The `Authorization` header is not passing at all. See pics:

![Screenshot 2023-12-09 14-39-39](https://github.com/honojs/middleware/assets/3282661/dedc5e07-5e75-4ff4-8d73-eba0a2e6bdd5)
![Screenshot 2023-12-09 14-39-49](https://github.com/honojs/middleware/assets/3282661/0210f9d5-eedb-42c9-89f4-45eec10c86cb)

I also tried using the Headers Schema:

```ts
const HeadersSchema = z.object({
  // Header keys must be in lowercase, `Authorization` is not allowed.
  authorization: z.string().openapi({
    example: "Bearer SECRET",
  })
});
```

but got this error:

```json
{
  "success": false,
  "error": {
    "issues": [
      {
        "code": "invalid_type",
        "expected": "string",
        "received": "undefined",
        "path": [
          "authorization"
        ],
        "message": "Required"
      }
    ],
    "name": "ZodError"
  }
}
```

Relevant Code:

```ts
import { OpenAPIHono, createRoute, z } from "@hono/zod-openapi";
import { swaggerUI } from "@hono/swagger-ui";
import { bearerAuth } from "hono/bearer-auth";

const app = new OpenAPIHono();

const token = "honoiscool";

app.use("/api/*", bearerAuth({ token }));

app.openAPIRegistry.registerComponent("securitySchemes", "", {
  type: "http",
  name: "Authorization",
  scheme: "bearer",
  in: "header",
  description: "Bearer token",
});

app.openapi(
  {
    method: "get",
    path: "/api/page",
    operationId: "page",
    security: [
      {
        bearerAuth: [], // also tried 'Bearer'
      },
    ],
    responses: {
      200: {
        description: "Respond to a message",
        content: {
          "application/json": {
            schema: z.object({
              message: z.string(),
            }),
          },
        },
      },
      401: {
        description: "no token",
        content: {
          "application/json": {
            schema: z.object({
              message: z.string(),
            }),
          },
        },
      },
    },
  },
  (c) => {
    return c.jsonT({
      message: "hello, the time is: " + new Date().toISOString(),
    });
  },
  (result, c) => {
    console.log(result);
    // console.log(c);
    if (!result.success) {
      return c.jsonT(
        {
          code: 400,
          message: "Validation Error",
        },
        400
      );
    }
  }
);

app.get('/api/page', (c) => {
  return c.json({ message: 'You are authorized' })
})
...
```

It almost seems to avoid the 401 spec, and skip the error hook too.

Any help would be great. I'm really at a loss here on how to address this. Thanks!

**Comment by yusukebe** [comment]
@sor4chi Can you see this issue?

**Comment by sor4chi** [comment]
https://github.com/honojs/middleware/issues/261

I'm busy and haven't been able to look at it, but maybe this issue will solve the problem?

It's not closed, but it should be resolved.

**Comment by yusukebe** [comment]
@bramses 

Can this solve your issue? https://github.com/honojs/middleware/issues/261

**Comment by sor4chi** [comment]
I'm personally concerned that the second argument of registerComponent is an empty string.

**Comment by bramses** [comment]
Hi both, thank you for the responses!

@sor4chi i tried a non empty string too -- did not work. It just seems to be the name loaded into Swagger.

@yusukebe my API code for `/api/page` is similar to #261 the only main difference is I'm using `app.use("/api/*", bearerAuth({ token }));`. It seems without this the route isnt actually authorized unless I'm missing something?

**Comment by sor4chi** [comment]
@bramses 
<img width="789" alt="スクリーンショット 2023-12-11 午後2 31 35" src="https://github.com/honojs/middleware/assets/80559385/487acb76-7e10-457a-9210-ef2b4e9d8a93">

The security option must be specified with the name registered in securitySchemes, as shown in the selection in this picture.
This worked for me, can you try it?

**Comment by bramses** [comment]
That worked for me as well! Thank you @sor4chi. Closing this issue with that fix.

**Comment by oieduardorabelo** [comment]
for future reference, in case you want to define the authentication to ALL your routes

you can add the `security` scheme in the global scope of the openapi definition (where you declare `openapi: 3.x.x`)

in that way, you don't need to declare `security` in each route

```ts
hono.openAPIRegistry.registerComponent('securitySchemes', 'Bearer', {
    type: 'http',
    scheme: 'bearer',
    bearerFormat: 'JWT',
});

hono.doc31('/openapi/json', (c) => ({
    openapi: '3.1.0',
    info: {
        version: '1.0.0',
        title: 'My API',
    },
    security: [
        {
            Bearer: [],
        },
    ],
    servers: [
        {
            url: new URL(c.req.url).origin,
            description: 'Current environment',
        },
    ],
}));

hono.openapi(
    createRoute({
        method: 'get',
        path: '/',
        responses: {
            200: {
                content: {
                    'application/json': {
                        schema: OK,
                    },
                },
            },
        },
    }),
    (c) => {
        return c.json({ ok: true }, 200);
    },
);
```

![CleanShot 2024-03-24 at 00 05 42](https://github.com/honojs/middleware/assets/829902/ff85fcbb-852c-4b4e-872c-9494369c185e)

openapi documentation:
https://swagger.io/docs/specification/authentication/bearer-authentication/

**Comment by sor4chi** [comment]
Hi, @csulit 

try this changes!

```diff
app.get(
  "/swagger",
  swaggerUI({
-    url: "/api/doc",
+    url: "/doc",
  })
);
```

**Comment by csulit** [comment]
> Hi, @csulit
> 
> could you try this changes?
> 
> ```diff
> app.get(
>   "/swagger",
>   swaggerUI({
> -    url: "/api/doc",
> +    url: "/doc",
>   })
> );
> ```

Actually I Can access swagger my only issue is the 401 error using OpenAPIHono

**Comment by csulit** [comment]
> @csulit
> 
> This is the entire Hono x OpenAPI x Swagger x Bearer Auth code that works at a minimum. If this does not solve your problem, please share the reproduction.
> 
> Code
> ```ts
> import { OpenAPIHono, z } from "@hono/zod-openapi";
> import { swaggerUI } from "@hono/swagger-ui";
> import { bearerAuth } from "hono/bearer-auth";
> 
> const app = new OpenAPIHono();
> 
> const token = "honoiscool";
> 
> app.use("/api/*", bearerAuth({ token }));
> 
> app.openAPIRegistry.registerComponent("securitySchemes", "Bearer", {
>   type: "http",
>   scheme: "bearer",
> });
> 
> app.openapi(
>   {
>     method: "get",
>     path: "/api/page",
>     operationId: "page",
>     security: [
>       {
>         Bearer: [],
>       },
>     ],
>     responses: {
>       200: {
>         description: "Responds with a greeting",
>         content: {
>           "application/json": {
>             schema: z.object({
>               message: z.string(),
>             }),
>           },
>         },
>       },
>       401: {
>         description: "Unauthorized",
>         content: {
>           "application/json": {
>             schema: z.object({
>               message: z.string(),
>             }),
>           },
>         },
>       },
>     },
>   },
>   (c) => {
>     return c.json({
>       message: "Hello from Hono!",
>     });
>   }
> );
> 
> app.get(
>   "/swagger",
>   swaggerUI({
>     url: "/doc",
>   })
> );
> 
> app.doc("/doc", {
>   info: {
>     title: "Hono OpenAPI Repro",
>     version: "v1.0.0",
>   },
>   openapi: "3.1.0",
> });
> 
> export default app;
> ```

```
import { clerkMiddleware, getAuth } from "@hono/clerk-auth";
import { swaggerUI } from "@hono/swagger-ui";
import { OpenAPIHono } from "@hono/zod-openapi";
import { bearerAuth } from "hono/bearer-auth";
import { cors } from "hono/cors";
import { getRouterName, showRoutes } from "hono/dev";
import { logger } from "hono/logger";
import { poweredBy } from "hono/powered-by";
import { prettyJSON } from "hono/pretty-json";
import { secureHeaders } from "hono/secure-headers";
import { corsConfig } from "./config/cors";
import { getPoolDb } from "./database";
import { ListingTypesRoute } from "./routes/listingTypes";
import { PropertyListingsRoute } from "./routes/propertyListings";
import { PropertyTypesRoute } from "./routes/propertyTypes";
import { customLogger } from "./utils/customLogger";

export type Env = {
  NODE_ENV: "development" | "production";
  DATABASE_URL: string;
};

const app = new OpenAPIHono<{ Bindings: Env }>();

const token = "honoiscool";

app.use("*", cors(corsConfig));
app.use("*", clerkMiddleware());
app.use("/api/*", bearerAuth({ token }));
app.use(logger(customLogger));
app.use(poweredBy());
app.use(prettyJSON());
app.use(secureHeaders());

app.openapi(PropertyTypesRoute, async (c) => {
  const { client, pool } = await getPoolDb(c.env.DATABASE_URL);
  const auth = getAuth(c);

  try {
    if (!auth?.user) {
      return c.json(
        {
          success: false,
          data: "Unauthorized",
        },
        { status: 401 }
      );
    }

    const query = await client.query("SELECT * FROM property_type");

    return c.json({
      success: true,
      data: query.rows,
    });
  } catch (error: any) {
    console.error(error);
    return c.json(
      {
        success: false,
        data: error.message,
      },
      { status: 500 }
    );
  } finally {
    pool.end();
  }
});

app.openapi(ListingTypesRoute, async (c) => {
  const { client, pool } = await getPoolDb(c.env.DATABASE_URL);
  const auth = getAuth(c);

  try {
    if (!auth?.user) {
      return c.json(
        {
          success: false,
          data: "Unauthorized",
        },
        { status: 401 }
      );
    }

    const query = await client.query("SELECT * FROM listing_type");

    return c.json({
      success: true,
      data: query.rows,
    });
  } catch (error: any) {
    console.error(error);
    return c.json(
      {
        success: false,
        data: error.message,
      },
      { status: 500 }
    );
  } finally {
    pool.end();
  }
});

app.openAPIRegistry.registerComponent("securitySchemes", "Bearer", {
  type: "http",
  scheme: "bearer",
});

app.get(
  "/swagger",
  swaggerUI({
    url: "/doc",
  })
);

app.doc("/doc", {
  info: {
    title: "Hono OpenAPI Repro",
    version: "v1.0.0",
  },
  tags: [{ name: "Property Listing" }],
  openapi: "3.1.0",
});
console.log(getRouterName(app));

showRoutes(app);

export default app;
```

**Comment by sor4chi** [comment]
Hmmm, looks like it's being used right...

```ts
    if (!auth?.user) {
      return c.json(
        {
          success: false,
          data: "Unauthorized",
        },
        { status: 401 }
      );
    }
```

You are not getting a 401 return on this part, are you?

**Comment by csulit** [comment]
> Hmmm, looks like it's being used right...
> 
> ```ts
>     if (!auth?.user) {
>       return c.json(
>         {
>           success: false,
>           data: "Unauthorized",
>         },
>         { status: 401 }
>       );
>     }
> ```
> 
> You are not getting a 401 return on this part, are you?

New code

```
import { clerkMiddleware, getAuth } from "@hono/clerk-auth";
import { swaggerUI } from "@hono/swagger-ui";
import { OpenAPIHono } from "@hono/zod-openapi";
import { bearerAuth } from "hono/bearer-auth";
import { cors } from "hono/cors";
import { getRouterName, showRoutes } from "hono/dev";
import { logger } from "hono/logger";
import { poweredBy } from "hono/powered-by";
import { prettyJSON } from "hono/pretty-json";
import { secureHeaders } from "hono/secure-headers";
import { corsConfig } from "./config/cors";
import { getPoolDb } from "./database";
import { ListingTypesRoute } from "./routes/listingTypes";
import { PropertyListingsRoute } from "./routes/propertyListings";
import { PropertyTypesRoute } from "./routes/propertyTypes";
import { customLogger } from "./utils/customLogger";

export type Env = {
  NODE_ENV: "development" | "production";
  DATABASE_URL: string;
};

const app = new OpenAPIHono<{ Bindings: Env }>();

const token = "honoiscool";

app.use("*", cors(corsConfig));
app.use("*", clerkMiddleware());
app.use("*", bearerAuth({ token }));
app.use(logger(customLogger));
app.use(poweredBy());
app.use(prettyJSON());
app.use(secureHeaders());

app.openAPIRegistry.registerComponent("securitySchemes", "Bearer", {
  type: "http",
  scheme: "bearer",
});

app.openapi(PropertyTypesRoute, async (c) => {
  const { client, pool } = await getPoolDb(c.env.DATABASE_URL);
  const auth = getAuth(c);

  try {
    if (!auth?.user) {
      return c.json(
        {
          success: false,
          data: "Unauthorized",
        },
        { status: 401 }
      );
    }

    const query = await client.query("SELECT * FROM property_type");

    return c.json({
      success: true,
      data: query.rows,
    });
  } catch (error: any) {
    console.error(error);
    return c.json(
      {
        success: false,
        data: error.message,
      },
      { status: 500 }
    );
  } finally {
    pool.end();
  }
});

app.get(
  "/swagger",
  swaggerUI({
    url: "/doc",
  })
);

app.doc("/doc", {
  info: {
    title: "Hono OpenAPI Repro",
    version: "v1.0.0",
  },
  tags: [{ name: "Property Listing" }],
  openapi: "3.1.0",
});

console.log(getRouterName(app));

showRoutes(app);

export default app;
```

The response is only a text

![image](https://github.com/honojs/middleware/assets/31933946/5b0475e2-8a42-4a19-8e1f-fa051b0234d2)

**Comment by csulit** [comment]
I need help understanding this section of my code. Can someone please explain it to me?

```
const token = "honoiscool";

app.use("*", bearerAuth({ token }));
```

**Comment by sor4chi** [comment]
Oh, OpenAPIHono doesn't have Bearer Auth functionality in the first place, and the Bearer Auth functionality in the Swagger UI is for the client, so it doesn't affect the server in any way.
To configure BearerAuth on the server side, import the Bearer Auth built-in middleware from `hono/bearer-auth` and use that for the route you want to protect with Bearer Auth.
For example, you want to apply Bearer Auth to routes under `/api` with the password `hello`,

```ts
import { bearerAuth } from "hono/bearer-auth";
app.use("/api/*", bearerAuth({ 
  token: "hello",
}));
```

So it becomes

**Comment by csulit** [comment]
> Oh, OpenAPIHono doesn't have Bearer Auth functionality in the first place, and the Bearer Auth functionality in the Swagger UI is for the client, so it doesn't affect the server in any way. To configure BearerAuth on the server side, import the Bearer Auth built-in middleware from `hono/bearer-auth` and use that for the route you want to protect with Bearer Auth. For example, you want to apply Bearer Auth to routes under `/api` with the password `hello`,
> 
> ```ts
> import { bearerAuth } from "hono/bearer-auth";
> app.use("/api/*", bearerAuth({ 
>   token: "hello",
> }));
> ```
> 
> So it becomes

I appreciate you @sor4chi thank you for your time!
