### ISSUE TITLE
Clerk middleware 401 errors

### ISSUE THREAD

**Issue by janat08** [honojs/middleware#308]
For some reason the moment that add clerkMiddleware I start getting 401 errors. I suspect that clerkbackend has updated or something. My project will brake on any route, I've tried removing the client script, and not calling clerk on backend, but it will still happen.

**Comment by yusukebe** [comment]
@janat08 Thank you for raising the issue.

@octoper Could you take a look at this?

**Comment by janat08** [comment]
I can't actually provide a minimal reproduction.

**Comment by janat08** [comment]
What makes me think that this is a bug is that it will happen after first live reload, and when I'm logged in with no route guards.

**Comment by lumberman** [comment]
I am encountering an issue.

If using `app.use("*", clerkMiddleware());` results in a 401 error on the favicon after redirecting back from the clerk login URL. 

Although the clerk login page indicates that I am signed in, `const auth = getAuth(c);` returns null. 

I am unsure if this issue is related to the URL. When I run `const auth = getAuth(c); console.log(auth?.debug());`, it shows that the 'host' is '127.0.0.1:50308', even though wrangler is running on localhost:XXXX.



```
// console.log(auth?.debug());

  apiKey: '',
  secretKey: 'sk_test',
  audience: '',
  apiUrl: 'https://api.clerk.dev',
  apiVersion: 'v1',
  frontendApi: 'advanced-vulture-[...].clerk.accounts.dev',
  proxyUrl: '',
  publishableKey: 'pk_test_[...],
  isSatellite: false,
  domain: '',
  jwtKey: '',
  searchParams: URLSearchParams(0) {},
  headerToken: undefined,
  origin: undefined,
  host: '127.0.0.1:50308',
  forwardedHost: undefined,
  forwardedPort: undefined,
  forwardedProto: undefined,
  referrer: undefined,
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  cookieToken: undefined,
  clientUat: '0',
  status: 'signed-out',
  reason: 'standard-signed-out',
  message: ''
  ```
  
  @yusukebe / @octoper can you please advice?

**Comment by lumberman** [comment]
I mean, can different hosts in wrangler vs node result in auth tokens/cookies not applying properly?

**Comment by csulit** [comment]
cloudflare worker template 401 error as well.

**Comment by csulit** [comment]
> @janat08 @lumberman @csulit
> 
> Sorry for the delayed reply. I can't produce it. If you can provide a minimal project to reproduce it, I'll take a look.

Is it necessary to make another call if only the userId is available and the user object is not present?

```
  const session = await clerkClient.sessions.getSession(auth.sessionId);
  const user = await clerkClient.users.getUser(auth.userId);
```

**Comment by yusukebe** [comment]
@csulit 

I don't know, but if you share a minimal project to reproduce it, I can investigate.

**Comment by csulit** [comment]
> @csulit 
> 
> I don't know, but if you share a minimal project to reproduce it, I can investigate.

Will create a sandbox for you.

**Comment by yusukebe** [comment]
Thanks!

**Comment by csulit** [comment]
> @csulit
> 
> I don't know, but if you share a minimal project to reproduce it, I can investigate.

```
app.use("/v1/*", clerkMiddleware());

app.openapi(PropertyTypesRoute, async (c) => {
  const { client, pool } = await getPoolDb(c.env.DATABASE_URL);
  const auth = getAuth(c);

  try {
    if (!auth?.user) {
      return c.json(
        {
          success: false,
          data: "Unauthorized",
        },
        { status: 401 }
      );
    }

    const query = await client.query("SELECT * FROM property_type");

    return c.json({
      success: true,
      data: query.rows,
    });
  } catch (error: any) {
    console.error(error);
    return c.json(
      {
        success: false,
        data: error.message,
      },
      { status: 500 }
    );
  } finally {
    pool.end();
  }
});
```

This line of code doesn't trigger

```
  if (!auth?.user) {
    return c.json(
      {
        success: false,
        data: "Unauthorized",
      },
      { status: 401 }
    );
  }
```

**Comment by csulit** [comment]
> > @csulit
> > I don't know, but if you share a minimal project to reproduce it, I can investigate.
> 
> ```
> app.use("/v1/*", clerkMiddleware());
> 
> app.openapi(PropertyTypesRoute, async (c) => {
>   const { client, pool } = await getPoolDb(c.env.DATABASE_URL);
>   const auth = getAuth(c);
> 
>   try {
>     if (!auth?.user) {
>       return c.json(
>         {
>           success: false,
>           data: "Unauthorized",
>         },
>         { status: 401 }
>       );
>     }
> 
>     const query = await client.query("SELECT * FROM property_type");
> 
>     return c.json({
>       success: true,
>       data: query.rows,
>     });
>   } catch (error: any) {
>     console.error(error);
>     return c.json(
>       {
>         success: false,
>         data: error.message,
>       },
>       { status: 500 }
>     );
>   } finally {
>     pool.end();
>   }
> });
> ```
> 
> This line of code doesn't trigger
> 
> ```
>   if (!auth?.user) {
>     return c.json(
>       {
>         success: false,
>         data: "Unauthorized",
>       },
>       { status: 401 }
>     );
>   }
> ```

![image](https://github.com/honojs/middleware/assets/31933946/43724146-3659-4387-a920-37f0660632d7)

**Comment by csulit** [comment]
> > > @csulit
> > > I don't know, but if you share a minimal project to reproduce it, I can investigate.
> > 
> > 
> > ```
> > app.use("/v1/*", clerkMiddleware());
> > 
> > app.openapi(PropertyTypesRoute, async (c) => {
> >   const { client, pool } = await getPoolDb(c.env.DATABASE_URL);
> >   const auth = getAuth(c);
> > 
> >   try {
> >     if (!auth?.user) {
> >       return c.json(
> >         {
> >           success: false,
> >           data: "Unauthorized",
> >         },
> >         { status: 401 }
> >       );
> >     }
> > 
> >     const query = await client.query("SELECT * FROM property_type");
> > 
> >     return c.json({
> >       success: true,
> >       data: query.rows,
> >     });
> >   } catch (error: any) {
> >     console.error(error);
> >     return c.json(
> >       {
> >         success: false,
> >         data: error.message,
> >       },
> >       { status: 500 }
> >     );
> >   } finally {
> >     pool.end();
> >   }
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This line of code doesn't trigger
> > ```
> >   if (!auth?.user) {
> >     return c.json(
> >       {
> >         success: false,
> >         data: "Unauthorized",
> >       },
> >       { status: 401 }
> >     );
> >   }
> > ```
> 
> ![image](https://private-user-images.githubusercontent.com/31933946/321471864-43724146-3659-4387-a920-37f0660632d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODk5NzIsIm5iZiI6MTcxMjg4OTY3MiwicGF0aCI6Ii8zMTkzMzk0Ni8zMjE0NzE4NjQtNDM3MjQxNDYtMzY1OS00Mzg3LWE5MjAtMzdmMDY2MDYzMmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAyNDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYTUwYTk3ZGVlMGJkM2I3MmFmOTY0MGQ4ZjZjNWU5MGZmZjBhYmQ4NzA2MGYxOGM0YzhlNzkyMjc0ZTNmNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xebjZS6PKlYIFTWqAWIwW7jnXfMODCBA3CmfOmob7dI)

Weirdly, the endpoint returns a JSON response when accessed through the Clerk SDK (Expo), but not when accessed with Postman.

![image](https://github.com/honojs/middleware/assets/31933946/3be7e527-ca5b-43d7-a184-5e28cddc290a)

**Comment by collinstommy** [comment]
Are there some headers set on the 401 response?

In my case, I was getting headers that indicated the auth reason was due to an expired token. The clerk token expires after 60 seconds so I had add the Clerk js frontend cleint on all HTML pages so that it can periodically refresh the token.

**Comment by janat08** [comment]
The issue was actually fixed. It was wrangler doing weird stuff with IP addresses.

**Comment by janat08** [comment]
Although perhaps there could additional code at determining if the misconfiguration weirdness is happening so as to not do false 401, defensive coding.
