### ISSUE TITLE
@hono/zod-validator doesn't support nullable values

### ISSUE THREAD

**Issue by not-reed** [honojs/middleware#348]
zod-validator seems to lose its types when a nullable is encountered
```ts
app.post("/",
  zValidator(
    "form", 
    z.object({ name: z.string() })
  ), 
  async (c) => {
    console.log({
      name: c.req.valid("form").name; // string
    })
  })
)
```

```ts
app.post("/",
  zValidator(
    "form", 
    z.object({ name: z.string().nullable() })
  ), 
  async (c) => {
    console.log({
      name: c.req.valid("form").name; // any
    })
  })
)
```

the validation itself works properly, however it breaks the `RPC / Client` feature on the front end as types are missing.

`.optional()` works as intended, however it only offers `type | undefined` and i'm looking for `type | undefined | null`

**Comment by yusukebe** [comment]
Hi @not-reed 

This is not a bug, but expected behavior. The data that `form` receives is not allowed to be `null`. So using `.nullable()` is not recommended.

This is because the actual value of `form` takes only `string | File | undefined`. If you want to handle `null`, use `json`.

**Comment by not-reed** [comment]
Oh yeah, that makes perfect sense. Thank you! Great work 😀
