### ISSUE TITLE
Type Error when trying to validate 'params' with zValidator - Types of parameters 'c' and 'c' are incompatible

### ISSUE THREAD

**Issue by and-rose** [honojs/middleware#351]
I might be missing something here but I can't seem to work my way around this type error when I try to use zValidator with my params schema.

```ts
// A snippet from my code
const racesParams = z.object({ seasonId: z.string() })

app.get('/season/:seasonId/races', zValidator('param', racesParams), async (c) => { // <-- type error with validator usage
  const { seasonId } = c.req.valid('param')

  return c.json(await getRaces(seasonId), 200)
})
```
I get this type error complaining about my usage of zValidator.
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'MiddlewareHandler<Env, string, { in: { param: { seasonId: string; }; }; out: { param: { seasonId: string; }; }; }>' is not assignable to parameter of type 'H<Env, "/season/:seasonId/races", {}, HandlerResponse<any>>'.
      Type 'MiddlewareHandler<Env, string, { in: { param: { seasonId: string; }; }; out: { param: { seasonId: string; }; }; }>' is not assignable to type 'MiddlewareHandler<Env, "/season/:seasonId/races", {}>'.
        Types of parameters 'c' and 'c' are incompatible.
          Type 'Context<Env, "/season/:seasonId/races", {}>' is not assignable to type 'Context<Env, string, { in: { param: { seasonId: string; }; }; out: { param: { seasonId: string; }; }; }>'.
            Property '#private' in type 'Context' refers to a different member that cannot be accessed from within type 'Context'.ts(2769)
types.d.ts(152, 5): The last overload is declared here.
```

I'm using bun 1.0.22 and my package.json looks like
```json
{
  "scripts": {
    "dev": "bun run --hot src/index.ts",
    "integration:test": "./scripts/run-integration-tests.sh",
    "migrate": "bun run src/migrate.ts"
  },
  "dependencies": {
    "@hono/zod-validator": "^0.1.11",
    "drizzle-orm": "^0.29.3",
    "hono": "^3.12.3",
    "postgres": "^3.4.3",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@faker-js/faker": "^8.3.1",
    "bun-types": "^1.0.7",
    "drizzle-kit": "^0.20.10",
    "moment": "^2.30.1",
    "postgres-interval": "^4.0.1"
  }
}
```

I've seen a few issues with similar struggles but nothing I could find seems to demo the usage of validating 'params' or fix my issue.

**Comment by luukvhoudt** [comment]
Copy, pasting the following test from this repo into my project resulted in the same type error.

https://github.com/honojs/middleware/blob/main/packages/zod-validator/test/index.test.ts

I see we got one thing in common, I'm also using Bun for my project. Now using Bun v1.0.23 and Hono v3.12.4

**Comment by and-rose** [comment]
Yeah, I just tried pasting my code into the repo's test case using Node v18.17.0 and didn't get the type error. This looks like a bun specific thing for sure.

**Comment by luukvhoudt** [comment]
With the intention to create a new issue over at the Bun repository I was trying to create a minimal reproducible example. However, I didn't manage to trigger the error or I did managed to get it working without a type error.

These are the steps I followed:

1. `bunx create-hono ./reproduction --template bun`
2. `cd reproduction/`
3. `bun add @hono/zod-validator zod`
4. `bun add --dev typescript`
5. Change the `src/index.ts`:
	```ts
	import { Hono } from 'hono'
	import { zValidator } from '@hono/zod-validator'
	import { z } from 'zod'
	
	const app = new Hono()
	
	app.get(
	  '/', 
	  zValidator('query', z.object({foo: z.string()})),
	  (c) => c.text('Hello Hono!'),
	)
	
	export default app
	```
6. Change the `tsconfig.json`:
	```json
	{
	  "compilerOptions": {
	    "target": "ES2022",
	    "moduleResolution": "bundler",
	    "esModuleInterop": true,
	    "strict": true,
	    "jsx": "react-jsx",
	    "jsxImportSource": "hono/jsx"
	  }
	}
	```
7. `bun --bun tsc`

Maybe our projects have certain settings in the `tsconfig.json`. I will get back to this issue some time later with the feedback of how this finding might have affected my project. Maybe I can figure out what setting caused the error.

**Comment by and-rose** [comment]
It might have something to do with adding the typescript dependency to the bun project? I couldn't 100% confirm that it's what helped but the second I ran `bun add --dev typescript` the error cleared from my project. Might be because the hono bun template doesn't have typescript in the package.json?

**Comment by yusukebe** [comment]
I can't reproduce it. No error occurs when I try @luukvhoudt's steps.

<img width="704" alt="Screenshot 2024-01-18 at 12 26 44" src="https://github.com/honojs/middleware/assets/10682/455c9a99-349c-4ef1-968c-e387f2bda496">

 The error may occur if the `hono` files referenced by `@hono/zod-validator` and `@hono/zod-validator` are different.

**Comment by and-rose** [comment]
I can confirm what fixed the issue on my WSL machine and MacOS was upgrading bun to v1.0.23 and `rm -rf`'ing my node_modules followed by a `bun i`

```sh
bun upgrade
rm -rf node_modules
bun i
```

You should be able to replicate the issue by downgrading back to v1.0.22 and reinstalling your node_modules. You can downgrade like this
```sh
curl -fsSl https://bun.sh/install | bash -s "bun-v1.0.22"
```

I'm happy to close this if this helps you guys too.
