### ISSUE TITLE
zod-openapi /doc endpoint returns 500 if param name is wrong

### ISSUE THREAD

**Issue by kornysietsma** [honojs/middleware#354]
Hi folks - we had some pain with a simple example of using `zod-openapi` because I mis-typed a parameter name.

A simplified case can be demponstrated using the example [in the docs](https://github.com/honojs/middleware/tree/main/packages/zod-openapi#basic-usage) - if you specify a parameter name 'foo' instead of 'id':

```js
const ParamsSchema = z.object({
  id: z
    .string()
    .min(3)
    .openapi({
      param: {
        name: 'foo',
        in: 'path',
      },
      example: '1212121',
    }),
})
```

Loading the `/doc` endpoint then returns a 500 error - with no logs, warnings or other messages that I could see.

The main pain was not so much the error, as diagnosing it!  Is there some way to see a log message or stack trace when an error like this occurs?

**Comment by yusukebe** [comment]
Hi @kornysietsma 

Thanks for creating the issue.

> The main pain was not so much the error, as diagnosing it! Is there some way to see a log message or stack trace when an error like this occurs?

This is certainly difficult to understand! I'll fix it now.
