### ISSUE TITLE
Cannot use preprocess and coerce in zValidator.

### ISSUE THREAD

**Issue by yodakaEngineer** [honojs/middleware#368]
hono v3.12.6
zValidator v0.1.11
typescript v5.3.2
zod v3.22.4

I get a type error on the zValidator line with the following code.

```
export const app = new Hono()

const route = app.get(
  '/posts/:id',
  zValidator(
    'query',
    z.object({
      page: z.preprocess((input) => parseInt(input), z.number().optional()),
    })
  ),
  (c) => {
    const a = c.req.valid('query').page
    // ...
    return c.json({
      title: 'Night',
      body: 'Time to sleep',
    })
  }
)
```

This is the error message.
```
 TS2769: No overload matches this call.
The last overload gave the following error.
Argument of type
MiddlewareHandler<Env, string, {   in: {     query: {       page?: unknown;     };   };   out: {     query: {       page?: number | undefined;     };   }; }>
is not assignable to parameter of type
H<Env, '/posts/:id', Input, Response & TypedResponse<JSONParsed<{   title: string;   body: string; }>>>
Type
MiddlewareHandler<Env, string, {   in: {     query: {       page?: unknown;     };   };   out: {     query: {       page?: number | undefined;     };   }; }>
is not assignable to type MiddlewareHandler<Env, '/posts/:id', Input>
Types of parameters c and c are incompatible.
Type Context<Env, '/posts/:id', Input> is not assignable to type
Context<Env, string, {   in: {     query: {       page?: unknown;     };   };   out: {     query: {       page?: number | undefined;     };   }; }>
Type Partial<ValidationTargets> | undefined is not assignable to type { query: { page?: unknown; }; }
Type undefined is not assignable to type { query: { page?: unknown; }; }
types.d.ts(152, 5): The last overload is declared here.
```

And I can't even use coerce.
I think each query value is defined string | undefined, so type mismatch occurred by after preprocess value.

**Comment by yusukebe** [comment]
If you want to validate a `query`, the result of `z.preprocess` must be a `string`. In your case it is `number`.

```ts
const schema = z.preprocess((input) => parseInt(input), z.number().optional())
const res = schema.parse('123')
type T = typeof res // number | undefined
```

So you get an error. This is because the value of a `query` is always a `string`.

**Comment by yusukebe** [comment]
@yodakaEngineer 

Please wait a bit, the Zod Validator may be able to support it.

**Comment by yodakaEngineer** [comment]
Thank you so much!!
Let me know if there is anything I can do to help!

**Comment by ludafa** [comment]
I think I found out root cause of this problem:

`@hono/zod-validator` uses the `z.input` to define middleware's input type. 

But `z.input` will return a wired result while coerce is used:

```ts
const schema = z.coerce.number();
type inputType = z.input<typeof schema>; // inputType is number
```


I wondor `z.coerce.number()` should have a set of valid input type, maybe the same to parseInt(str: string) or Number(val: any)'s input type. Not sure. Or just return unknown or any. If so, zValidator would work fine.

To fix this temporarily, you can use the line to make zod work:

```ts
zValidator(
  'query',
  z.object({
    numeric_id: z.string().pipe(z.coerce.number().int().min(0)) // make the input type `string`,
    any_id: z.any().pipe(z.coerce.number().int().min(0)) // make the input type `any`
  }),
)
```

Clearly, it is a little bit verbose. 

Maybe `@hono/zod-validator` could change a better solution instead of `z.input`?

**Comment by yusukebe** [comment]
Hi @yodakaEngineer!

With the new Hono `v4.0.9` the following code works as you expect.

```ts
import { Hono } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { z } from 'zod'

export const app = new Hono()

const route = app.get(
  '/posts/:id',
  zValidator(
    'query',
    z.object({
      page: z.coerce.number()
    })
  ),
  (c) => {
    const a = c.req.valid('query').page // a is number
    // ...
    return c.json(0)
  }
)
```

@ludafa 

Does this solve your problem?

**Comment by ludafa** [comment]
@yusukebe this fixed the server side code but broke client side code with the hono client.

![image](https://github.com/honojs/middleware/assets/6285928/85359f88-93a1-4c9f-bb79-4c55e6a77f38)

**Comment by yusukebe** [comment]
Hi @yodakaEngineer @ludafa 

I've add the change #411 for supporting `coerce` in Zod Validator and release the new version "v0.2.0". Try it!

**Comment by yodakaEngineer** [comment]
@yusukebe I tried it only preprocess but it works!!
Thank you!
