### ISSUE TITLE
How to Insert Custom Middleware Using @hono/zod-openapi ?

### ISSUE THREAD

**Issue by poteboy** [honojs/middleware#379]
I'm trying to use custom middleware with `@hono/zod-openapi` to enhance request handling by inserting custom logic and types. However, it seems like the current setup does not allow middleware to be inserted in a way that the types are extended or accessible within the handler that follows.

## Current Behavior 

Using Hono normally, I can insert middleware and extend types as follows:

```ts
export const middleware = createMiddleware<{
  Variables: {
    userId: string;
  };
}>(async (c, next) => {
  const userId = await getUserId();
  c.set("userId", userId);
  await next();
});

app.get("/me", middleware, async (c) => {
  const userId = c.var.userId
  const user = await someORM.user.findUnique({ where: { id: userId } });
  return c.json(user);
});
```
## Desired Behavior with @hono/zod-openapi

I would like to achieve a similar pattern with @hono/zod-openapi, but it's unclear how to properly insert middleware that extends the context or request types.

```ts
export const app = new OpenAPIHono().openapi(
  createRoute({
    method: "get",
    path: "/me",
    responses: {
      200: {
        description: "OK",
        content: {
          "application/json": {
            schema: z.object({
              name: z.string(),
            }),
          },
        },
      },
    },
  }),
  middleware, // Attempting to use middleware here
  async (c) => {
    return c.json({ name: "hello world" });
  },
);
```

Is there a recommended way to insert custom middleware with @hono/zod-openapi that allows for extending types or injecting custom logic into the request handling flow?

**Comment by yusukebe** [comment]
Hi @poteboy !


```ts
app.openapi(route, handler, hook)

https://github.com/honojs/middleware/tree/main/packages/zod-openapi#configure-middleware-for-each-endpoint

```ts
import { OpenAPIHono, createRoute } from '@hono/zod-openapi'
import { z } from 'zod'
import { createMiddleware } from 'hono/factory'

type Env = {
  Variables: {
    userId: string
  }
}

export const middleware = createMiddleware<Env>(async (c, next) => {
  const userId = '123'
  c.set('userId', userId)
  await next()
})

export const app = new OpenAPIHono<Env>()

const route = createRoute({
  method: 'get',
  path: '/me',
  responses: {
    200: {
      description: 'OK',
      content: {
        'application/json': {
          schema: z.object({
            name: z.string()
          })
        }
      }
    }
  }
})

app.use(route.getRoutingPath(), middleware)

app.openapi(route, (c) => {
  const userId = c.var.userId
  return c.json({ name: `Hello from ${userId}` })
})

export default app
```

**Comment by poteboy** [comment]
@yusukebe 
Ah, I see. This is exactly what I wanted to know. Thank you!

**Comment by askorupskyy** [comment]
@yusukebe 

> So, use [the method described in the documentation](https://github.com/honojs/middleware/tree/main/packages/zod-openapi#configure-middleware-for-each-endpoint).
> 
> ```ts
> import { prettyJSON } from 'hono/pretty-json'
> import { cache } from 'honoc/cache'
> 
> app.use(route.getRoutingPath(), prettyJSON(), cache({ cacheName: 'my-cache' }))
> app.openapi(route, handler)
> ```
> 
> You cannot just pass only the custom middleware for type inference for variables, here you need to pass the `Env` includes `Variables` to the `app`.
> 
> All code should look like this:
> 
> ```ts
> import { OpenAPIHono, createRoute } from '@hono/zod-openapi'
> import { z } from 'zod'
> import { createMiddleware } from 'hono/factory'
> 
> type Env = {
>   Variables: {
>     userId: string
>   }
> }
> 
> export const middleware = createMiddleware<Env>(async (c, next) => {
>   const userId = '123'
>   c.set('userId', userId)
>   await next()
> })
> 
> export const app = new OpenAPIHono<Env>()
> 
> const route = createRoute({
>   method: 'get',
>   path: '/me',
>   responses: {
>     200: {
>       description: 'OK',
>       content: {
>         'application/json': {
>           schema: z.object({
>             name: z.string()
>           })
>         }
>       }
>     }
>   }
> })
> 
> app.use(route.getRoutingPath(), middleware)
> 
> app.openapi(route, (c) => {
>   const userId = c.var.userId
>   return c.json({ name: `Hello from ${userId}` })
> })
> 
> export default app
> ```

Just ran into an issue with this:

```typescript
authRouter.use(contract.auth.logout.path, useAuth);

authRouter.openapi(contract.auth.logout, async (c) => {
  if (!c.var.user || !c.var.sessionId) {
    return c.json({ message: 'Unauthorized' }, 401);
  }

  deleteSession(c, { userId: c.var.user.id, sessionId: c.var.sessionId });
  return c.json({ message: 'Success' }, 200);
});

export { authRouter };
```

The `authRouter` exported below does not have `auth.logout` in its type so I do not get any RPC for this endpoint. Is there any way this has been fixed since?

**Comment by yusukebe** [comment]
@askorupskyy 

Hmm. I can't investigate without knowing what the `contract.auth.logout` is, but should it assign the return value as a variable like `authRoutes`?

```ts
const authRoutes = authRouter.openapi(contract.auth.logout, async (c) => {
    // ...
})

export type authRoutesType = typeof authRoutes
```

**Comment by askorupskyy** [comment]
@yusukebe it ended up being a weird typescript thing. basically every time you call `.openapi` `.get` `.post` or etc on a Hono instance, it extends the type of that instance with the Handler type.

Don't mind the `contract.logout` thing, it's just where I store the routes created using `createRoute` I keep them in a separate NX lib.

Such that with the example below you get the full client:

```typescript
export const app = new OpenAPIHono().openapi(endpointOne, () => {}).openapi(endpointTwo, () => {})
```

But with this one you don't

```typescript
const app = new OpenAPIHono();

app.openapi(endpointOne, () => {})
app.openapi(endpointTwo, () => {})

export { app }
```

This is because the type of app has not been extended.

Now since when applying middleware I can't do `.openapi()` after doing `.use()`, I have to do it like this:

```typescript
const router = new OpenAPIHono<{
  Variables: AuthenticatedMiddlewareVariables;
}>();

router.use(contract.auth.me.path, authMiddleware);
router.use(contract.auth.logout.path, authMiddleware);

export const authRouter = router
  .openapi(contract.auth.signin, async (c) => {})
  .openapi(contract.auth.signup, async (c) => {})
  .openapi(contract.auth.logout, async (c) => {})
```

Doing middleware like this introduces some inconveniences though. 
For example I cannot do middleware X for `GET /` and middleware Y for `POST /`. Both endpoints will have two middleware handlers like I could by doing `.get('/path', middlewareHandler, handler)`.

**Comment by askorupskyy** [comment]
@yusukebe 

Doing this,

```
const create = createRoute({
  method: 'post',
  path: '/',
  middleware: [usePermissions(['create'])],
})
```

Does not work at all either.
