### ISSUE TITLE
`@hono/zod-openapi` is not compatible with HonoX

### ISSUE THREAD

**Issue by bruceharrison1984** [honojs/middleware#416]
Attempting to use `@hono/zod-openapi` with HonoX results in the following error:

![image](https://github.com/honojs/middleware/assets/17836372/f83d10d6-8107-4e8e-a40b-cb0edb16bf83)

The following was (attempted) used to get this going:
```ts
//server.ts
import { OpenAPIHono } from '@hono/zod-openapi';
import { createApp } from 'honox/server';
import { showRoutes } from 'hono/dev';
import errorHandler from './routes/_error';

const openApi = new OpenAPIHono();

const app = createApp({
  app: openApi,
  init: (app) => {
    app.onError(errorHandler);
  },
});

showRoutes(app);

export default app;
```
It doesn't seem to matter where in the router tree `@hono/zod-openapi` is injected, the error persists until it is replaced with normal `hono` instances.

**Comment by yusukebe** [comment]
Hi @bruceharrison1984 

This is because `@asteasolutions/zod-to-openapi` used internally by Zod OpenAPI does not support ES Modules. So, the error will not occur if you set `vite.config.ts` as follows.

```ts
export default defineConfig({
  ssr: {
    external: ['@asteasolutions/zod-to-openapi']
  },
  plugins: [honox()]
})
```

**Comment by bruceharrison1984** [comment]
Awesome, I wondered if it was something along those lines. Thanks!

**Comment by yusukebe** [comment]
Yeah, the matter of CommonJS/ES Modules is annoying.
