### ISSUE TITLE
[zod-openapi][feature request] set route specific middleware from zod-openapi createRoute

### ISSUE THREAD

**Issue by flipvh** [honojs/middleware#417]
We love working with hono/zod-openapi and hono in general. We do have a challenge with configuring route-specific middleware in a way that is both maintainable, readable and secure (the last argument being that you make it very difficult for developer to simply forget making an api route secure enough).

Our goal was to support per route a different combination of middleware. such as, but not limited to:
- rate limiting with varying config
-  guard middleware with varying protection levels. For example just check authentication, check tenant (for high-sec multi-tenant systems), system admin level check with fixed ip requirement etcetera. Or simply a route that allows public access.
- The guard level needs to be made explicitly on each route: public, auth, tenant or system level. This way its pretty difficult to forget about it?

You can already create route-specific middleware but you get sort of a duplication of your entire route configuration - if you also use zod-openapi?

Our conclusion was to implement it in the createRoute step, but because this is not supported by `hono/zod-openapi`, we now created an abstraction layer that resolves into createRoute. See an example below and the complete work here: https://github.com/cellajs/cella/blob/a51e182662cbcd3db8575dec4356c78203129013/backend/src/types/common.ts.

```
guard: RouteConfig['guard'];
middlewares: RouteConfig['middlewares'];
```

Our question is if this solution of ours could also be beneficial to others that use hono/zod-openapi and developer using  hono in general. It could improve the flexibility of setting middleware like also superficially discussed in this Twitter thread? https://twitter.com/jullerino/status/1763525247477641688

Or perhaps there are other ways to achieve the same results?

**Comment by yusukebe** [comment]
Hi @flipvh !

I might not be able to fully understand your demand, but have you ever tried `route.getRoutingPath()`?

https://github.com/honojs/middleware/tree/main/packages/zod-openapi#configure-middleware-for-each-endpoint

**Comment by flipvh** [comment]
Thanks! Yes, we did that before but if becomes a bit messy if you have 40 routes or more. It feels and looks like duplicating your entire list of routes, which is not very readable and also not very DRY.

I realize I might be asking (too) much, but having the ability to pass middleware in the createRoute would really be an amazing improvement imo in terms of the developer experience of hono's zod-openapi, which seems quite popular among the community. 

An alternative - since there might be other variations of my request - is simply to make it easier to add a custom wrapper around the createRoute, so each developer can have more flexibility, while the zod-openapi stays clean. 

Thanks again, Flip

**Comment by yusukebe** [comment]
@flipvh I'm getting the points!

Then, super simple, how about making an `app.openapi` accept Middleware?

```ts
app.openapi(middleware1, middleware2, route, (c) => {
  // ...
  return c.json()
})
```

However, I intentionally made it not accept Middleware in order to avoid type complexity. Anyway, whether we implement it or not, I want to know if this method will solve your problem.

**Comment by flipvh** [comment]
Hi @yusukebe That could work but we prefer something like this: https://github.com/honojs/middleware/pull/435/commits/23d3d330dcbd58541b813efd112f495a84fd37db

That would allow us to do something like this in `createRoute`: 
```
middlewares: [Guard.SystemAdmin, RateLimit({options})]
```
What do you think?

**Comment by nicobytes** [comment]
I have a similar case, for example I would like to have some endpoints publics without jwt validation and others with jwt validation, I used `route.getRoutingPath()` but this method validates just the path without method, therefore other endpoints with the same path requies the jwt token.

```ts
// Post enpoint

const postRoute = createRoute({
  method: 'post',
  path: '/api/v1/users',
  ....
});

app.use(postRoute.getRoutingPath(), jwtMiddleware);
app.openapi(route, (c) => {
  return c.json(...})
})

// Get endpoint

const getRoute = createRoute({
  method: 'get',
  path: '/api/v1/users',
  ...
});

app.openapi(getRoute, (c) => {
  return c.json({...})
})
```

In this case, both endpoints require the JWT validation, I could create something like this,

```ts
app.use(route.getRoutingPath(), async (c, next) => {
  if (c.req.method === 'POST') {
    return jwtMiddleware(c, next);
  }
  await next();
});
```

But the approach of adding middleware as a part of createRoute I like it. 

`middlewares: [Guard.SystemAdmin, RateLimit({options})] `
