### ISSUE TITLE
[zod-openapi] How to make request-body optional?

### ISSUE THREAD

**Issue by oskarkivra** [honojs/middleware#424]
I have the following schema:
```ts
const route = createRoute({
  method: 'post',
  path: '/users',
  request: {
    body: {
      required: false,
      content: {
        'application/json': {
          schema: z
            .object({
              name: z.string().optional(),
            })
            .optional(),
        },
      },
    },
  },
});

app.openapi(route, (c) => {
  const { name } = c.req.valid('json');
  return c.json({ name });
});
```

It is working fine as long as I include a valid and non empty body but I want to make it possible to send an empty body. But when I try I get the error message: `HTTPException [Error]: Invalid HTTP header: Content-Type=undefined`. Is this a bug or am I doing something wrong?

I have created a demo project here: https://stackblitz.com/edit/stackblitz-starters-tpxv6f?file=index.js

**Comment by yusukebe** [comment]
Hi @oskarkivra !

This is not a bug, but intended behavior. Also, it is not about Zod OpenAPI, but about the validator in the Hono core.

If the appropriate content type is not set in the request header, an error will occur. Also, in this case, even if the `application/json` header is set, you will get a `Malformed JSON in request body` error because the body is empty.

**Comment by oskarkivra** [comment]
@yusukebe Thanks for you reply but I don't get it. Are you saying it is not possible to make a POST request with hono without a body?

**Comment by yusukebe** [comment]
@oskarkivra 

> Are you saying it is not possible to make a POST request to a hono server without a body?

Hono core server accepts POST requests without a body, but Zod OpenAPI uses a validator, so it behaves as just described.

**Comment by oskarkivra** [comment]
@yusukebe Okey but isn't that validation wrong in that case? I mean why do hono have a validation that requirer the content type header? Shouldn't it be optional?

**Comment by yusukebe** [comment]
> I mean why do hono have a validation that requirer the content type header?

It follows that [`Request.formData()`](https://developer.mozilla.org/en-US/docs/Web/API/Request/formData) used internally will throw an error if the content type is wrong.

```ts
app.post('/', async (c) => {
  const form = await c.req.formData()
  // ^^ throw error if the content type is wrong
  // TypeError: Unrecognized Content-Type header value. FormData can only parse the following MIME types: multipart/form-data, application/x-www-form-urlencoded
})
```

But as you said, for Zod OpenAPI, it will not be friendly for users if it throws an error though `request.body.required` in the schema is `false`.

**Comment by oskarkivra** [comment]
It anyone else having the same issue; I made a ugly hack to get around this:
```ts
app.use('/api/*', async (c, next) => {
  const contentType = c.req.header('Content-Type');
  const method = c.req.method;
  if (method !== 'GET' && !contentType) {
    c.req.raw.headers.set('Content-Type', 'application/json');
    const clone = c.req.raw.clone();
    const body = await clone.text();

    if (!body) {
      c.req.raw = new Request(clone, {
        body: JSON.stringify({}),
      });
    }
  }
  await next();
})
```

**Comment by oskarkivra** [comment]
I'm closing this since the issue seams to be in hono and not in the openapi middleware
