### ISSUE TITLE
Zod OpenAPI: Types export

### ISSUE THREAD

**Issue by arsaizdihar** [honojs/middleware#432]
I want to make wrapper functionality on createRoute that inject 400 errors in every route, but I can't access the internal typing like RouteConfig, ResponseConfig, etc. I suggest to export all the core typings.

**Comment by flipvh** [comment]
Hi @arsaizdihar, sounds interesting. Could this be related to our feature request? https://github.com/honojs/middleware/issues/417

**Comment by yusukebe** [comment]
Hi @arsaizdihar !

Sorry for the delayed response.

The types are exported from [Zod to OpenAPI](https://github.com/asteasolutions/zod-to-openapi) which is used in Zod OpenAPI. So you can use them like the following:

```ts
import type { ResponseConfig, RouteConfig } from '@asteasolutions/zod-to-openapi'
```
