### ISSUE TITLE
Importing @hono/zod-openapi in cloudflare worker vitest environment fails

### ISSUE THREAD

**Issue by JonasHiltl** [honojs/middleware#436]
Cloudflare recently [announced](https://blog.cloudflare.com/workers-vitest-integration) their new testing integration with vitest to test workers directly in a workers environment.

When trying it out myself I stumbled about this bug caused by `@hono/zod-openapi` because it can't import `@hono/zod-validator`. But if you look closely at the error message you can see that `@hono/zod-openapi` tries to import `@hono/zod-validator` from `.../dist/@hono/zod-validator` but that path is wrong, since dependencies are not located in `dist`.
```
[vpw:inf] Starting isolated runtimes for vitest.config.ts...
workerd/server/server.c++:2789: error: Fallback service failed to fetch module; payload = ; spec = /?specifier=%2FUsers%2F...%2Foapi-bug%2Fnode_modules%2F%40hono%2Fzod-validator%2Fdist%2Fesm%2Findex.js&referrer=%2FUsers%2F...%2Foapi-bug%2Fnode_modules%2F%40hono%2Fzod-openapi%2Fdist%2Findex.mjs
 ❯ test/index.spec.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/index.spec.ts [ test/index.spec.ts ]
Error: No such module "Users/.../oapi-bug/node_modules/@hono/zod-openapi/dist/@hono/zod-validator".
  imported from "Users/.../oapi-bug/node_modules/@hono/zod-openapi/dist/index.mjs"
```

Here is a minimal [repo](https://github.com/JonasHiltl/oapi-bug) to reproduce the bug.
The bug is caused by just importing from `@hono/zod-openapi`, so this is enough
```ts
import { OpenAPIHono } from "@hono/zod-openapi";
import { test } from "vitest";

test("test", () => {
  const app = new OpenAPIHono();
})
```

This smells like an `esm` error to me, but I'm not sure why it searches for the dependency in `dist` 🤷‍♂️

**Comment by yusukebe** [comment]
Hi @JonasHiltl 

Thanks for raising the issue and creating the repro.

I've released the new version of `@hono/zod-openapi`. This will fix the "Hono-side" problem. But, unfortunately, [Zod to OpenAPI](https://github.com/asteasolutions/zod-to-openapi), which is used in `@hono/zod-open API`, is not supporting ESM now. So the following error will thrown.

```
 FAIL  test/index.spec.ts [ test/index.spec.ts ]
TypeError: Cannot use require() to import an ES Module.
 ❯ Users/yusuke/work/h/oapi-bug/node_modules/openapi3-ts/dist/oas30-CAmzubQd.js:1:22
 ❯ Users/yusuke/work/h/oapi-bug/node_modules/openapi3-ts/dist/oas30.js?mf_vitest_no_cjs_esm_shim:1:27
 ❯ Users/yusuke/work/h/oapi-bug/node_modules/@asteasolutions/zod-to-openapi/dist/index.js?mf_vitest_no_cjs_esm_shim:35
```

**Comment by yusukebe** [comment]
@JonasHiltl 

This issue has been fixed completely with the new version `@hono/zod-openapi@0.10.0`. Try it!
