### ISSUE TITLE
packages/esbuild-transpiler#deno--deno-deploy: transpiled TypeScript served with incorrect MIME type

### ISSUE THREAD

**Issue by mfulton26** [honojs/middleware#441]
Following the [esbuild Transpiler Middleware Deno / Deno Deploy](https://github.com/honojs/middleware/tree/c56b22f15ad9203d46b15440bd7764e45d244b99/packages/esbuild-transpiler#deno--deno-deploy) successfully transpiles `/static/*` files but the MIME type is incorrect which prevents browsers from loading them.

e.g.

```js
await import("http://localhost:8000/static/foo.ts")
```

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "video/mp2t". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by yusukebe** [comment]
Hi @mfulton26 !

This may be fixed in the new version `0.1.3`. Try it!
