### ISSUE TITLE
Middleware with pre-v1 peerDependencies installs old version of them

### ISSUE THREAD

**Issue by yudai-nkt** [honojs/middleware#442]
I started using Valibot validator middleware and noticed that the installed Valibot is quite old. There are 22 releases between the installed (0.13.1) and the latest (0.30.0) versions.

This is because peer deps are declared with a caret notation and `^0.13.1` doesn't match 0.14.0 and later.

https://github.com/honojs/middleware/blob/c56b22f15ad9203d46b15440bd7764e45d244b99/packages/valibot-validator/package.json#L29-L32

This is particularly problematic when a middleware is installed in a project where its peer deps are already used. An `ERESOLVE` error is issued and you fail to install the middleware:

```console
$ npm install valibot
$ npm install @hono/valibot-validator
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: hono-middleware-repro@1.0.0
npm ERR! Found: valibot@0.30.0
npm ERR! node_modules/valibot
npm ERR!   valibot@"^0.30.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer valibot@"^0.13.1" from @hono/valibot-validator@0.2.2
npm ERR! node_modules/@hono/valibot-validator
npm ERR!   @hono/valibot-validator@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/ynkt/.npm/_logs/2024-04-06T18_55_32_176Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/ynkt/.npm/_logs/2024-04-06T18_55_32_176Z-debug-0.log
```

Semver like `>=0.13.1 <1` would be preferred so that users can have access to Valibot's new features, but I don't have time to investigate if there are incompatibilites that break `@hono/valibot-validator` between 0.13.1 and 0.30.0. Breaking changes might be OK because `@hono/valibot-validator` is pre-v1 as well.

I'd like to hear your opinion on this problem before working on a PR. What do you think?

**Comment by yudai-nkt** [comment]
Based on [the search result](https://github.com/search?q=repo%3Ahonojs%2Fmiddleware+peerDependencies+language%3AJSON&type=code&l=JSON), below is a list of middlewares besides `@hono/valibot-validator` that have v0.x peer dependencies:

https://github.com/honojs/middleware/blob/c56b22f15ad9203d46b15440bd7764e45d244b99/packages/auth-js/package.json#L54-L58

https://github.com/honojs/middleware/blob/c56b22f15ad9203d46b15440bd7764e45d244b99/packages/clerk-auth/package.json#L26-L29

https://github.com/honojs/middleware/blob/c56b22f15ad9203d46b15440bd7764e45d244b99/packages/typebox-validator/package.json#L29-L32

Auth.js middleware looks OK in terms of this issue.

**Comment by yusukebe** [comment]
Hi @yudai-nkt 

> I'd like to hear your opinion on this problem before working on a PR. What do you think?

I think it will not be a problem if we allow the new Valibot version with `peerDependencies`. It is a more significant problem that it doesn't work with the new Valibot.

**Comment by yudai-nkt** [comment]
thanks for the answer! ok, i'll work on a PR (possibly on the weekend)

**Comment by cluah** [comment]
yeah, trying to use valibot right now:

```$ npm add valibot @hono/valibot-validator
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: undefined@undefined
npm WARN Found: valibot@0.13.1
npm WARN node_modules/valibot
npm WARN   valibot@"*" from the root project
npm WARN   1 more (@hono/valibot-validator)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer valibot@"^0.13.1" from @hono/valibot-validator@0.2.2
npm WARN node_modules/@hono/valibot-validator
npm WARN   @hono/valibot-validator@"*" from the root project```

**Comment by cluah** [comment]
yeah, I was trying to use valibot

```$ npm add valibot @hono/valibot-validator
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: undefined@undefined
npm WARN Found: valibot@0.13.1
npm WARN node_modules/valibot
npm WARN   valibot@"*" from the root project
npm WARN   1 more (@hono/valibot-validator)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer valibot@"^0.13.1" from @hono/valibot-validator@0.2.2
npm WARN node_modules/@hono/valibot-validator
npm WARN   @hono/valibot-validator@"*" from the root project```
