### ISSUE TITLE
access hono context from trpc route

### ISSUE THREAD

**Issue by benjamine** [honojs/middleware#455]
when running hono in cloudflare, I'd need the hono context to access for example a D1 db at `c.env.DB`.
In general I think the trpc routes should get access to the hono context.

This could be achieved by adding a `createContext` parameter to `trpcServer` but if provided as a parameter it won't have access to the specific hono context,

this could be done modifying `tprcServer` implementation [here](https://github.com/honojs/middleware/blob/ffd67e5412815cd407ecab31ea10d23b7f5a761c/packages/trpc-server/src/index.ts#L9-L18) like this:

``` ts
export const trpcServer = ({
	endpoint = "/trpc",
	...rest
}: tRPCOptions): MiddlewareHandler => {
	return async (c) => {
		const res = fetchRequestHandler({
			...rest,
			endpoint,
			req: c.req.raw,
			createContext: () => ({
				env: c.env,
			}),
		});
		return res;
	};
};
```

although maybe a more generic solution is preferrable (this would interfere with a `createContext` provided as config in `rest`)

**Comment by yusukebe** [comment]
Hi @benjamine Thank you for raising the issue.

> this could be done modifying `tprcServer` implementation [here](https://github.com/honojs/middleware/blob/ffd67e5412815cd407ecab31ea10d23b7f5a761c/packages/trpc-server/src/index.ts#L9-L18) like this:

This seems to be good! Can you create the PR with this change and tests?

**Comment by benjamine** [comment]
@yusukebe I gave it a try at #458 , similar to the code example above, but I also allowed people to specify a `createContext` without breaking the expected behavior, and still have control to customize how data is copied from hono context if they want to.
