### ISSUE TITLE
hono/zod-openapi route groups don't populate into doc endpoint

### ISSUE THREAD

**Issue by DaveLo** [honojs/middleware#493]
Following along the route groups documentation with openapi and the app is functional, but the openapi docs are empty. If I move the customer route into the main app file the docs generate as expected.

```typescript
//customers.ts

const customers = new OpenAPIHono<EnvBindings>();

const customerRoute = createRoute({
  method: "get",
  path: "/{id}"
  request: { ...request schema }
  responses: { ...response schema }
});

customers.openapi(customerRoute, (c) => c.json({foo:'bar'}));

export default customers;

// main.ts
import customers from "./customers";

const app = new OpenAPIHono<EnvBindings>();
app.route("/customers", customers);

app.doc("/doc", {
  openapi: "3.0.0",
  info: { title: "my api" }
});

export const handler = handle(app)
```

## Expected behavior

The generated openapi doc in the separate file merges with the main app to stitch the api together.

## Actual behavior

The `/doc` route displays an empty `{}`

**Comment by tialki** [comment]
Not the same OpenAPIHono instances?

**Comment by DaveLo** [comment]
> Not the same OpenAPIHono instances?

No, I was trying to use [route grouping](https://hono.dev/api/routing#grouping) with the openapi middleware. Would I need to pass the app around more like a dependency injection to a create{X}Routes function? I'm trying to colocate the code and the route for clarity in maintaining each base route branch.

**Comment by vthang95** [comment]
I encountered the same issue after separating APIs into multiple route files.

**Comment by akineko** [comment]
It seems that the type information is lost if the return value of the openapi method is not received, probably because the type information is needed to generate OpenAPI documentation.

```ts
//customers.ts
const customers = new OpenAPIHono<EnvBindings>();

const customerRoute = createRoute({
  method: "get",
  path: "/{id}"
  request: { ...request schema }
  responses: { ...response schema }
})

// return value of the openapi method is required
const customersRouter = customers.openapi(customerRoute, (c) => c.json({foo:'bar'}))

export default customersRouter

// main.ts
import customersRouter from "./customers"

const app = new OpenAPIHono<EnvBindings>()
app.route("/customers", customersRouter)

app.doc("/doc", {
  openapi: "3.0.0",
  info: { title: "my api" }
})

export const handler = handle(app)
```

If you define multiple APIs, you need to write them in a method chain.

```ts
const customersRouter = customers
  .openapi(customerRoute, (c) => c.json({foo:'bar'}))
  .openapi(secondRoute, (c) => c.json({foo:'foo', bar: 'bar'}))
```

As another hint, handlers can also be defined separately.

```ts
const customerHandler: RouteHandler<typeof customerRoute> = (c) => c.json({foo: 'bar'})

const customersRouter = customers
  .openapi(customerRoute, customerHandler)
```

I am experimenting with this and will share more as I learn more.

**Comment by raiyansarker** [comment]
Having the same issue, is there any update so far?

**Comment by jilv220** [comment]
Same here.

**Comment by yusukebe** [comment]
Hi, I can't reproduce it. Can anyone share a minimal project to reproduce it? Thanks.

**Comment by DaveLo** [comment]
> Hi, I can't reproduce it. Can anyone share a minimal project to reproduce it? Thanks.

I just tried to produce a minimal example and it looks like it has been fixed in one of the minor updates since the version I was using when I had the problem. (v0.14.2 generates docs correctly using a node server handler)
