### ISSUE TITLE
Access user object returned by middleware

### ISSUE THREAD

**Issue by ilshm** [honojs/middleware#507]
I am currently implementing authentication in my application using the Bearer Auth Middleware. I'm interested in accessing additional information about the user associated with the token. Does this functionality only work when using JWT (JSON Web Tokens)?

Example:

```
import { Hono } from 'https://deno.land/x/hono/mod.ts'
import { bearerAuth } from 'https://deno.land/x/hono/middleware.ts'

const app = new Hono()
const token = 'honoiscool'

app.use(
  '/auth-verify-token/*',
  bearerAuth({
    verifyToken: async (token, c) => {
      // How to pass user from here to request?
      return token === dbQuery
    },
  })
)

app.get('/auth-verify-token/page', (c) => {
  return c.json({ message: `Your user id is ${c.user.id}` })
})
```

Thanks.

**Comment by yusukebe** [comment]
Hi @ilshm 

Try to use `c.set()/c.get()`: https://hono.dev/api/context#set-get

**Comment by yusukebe** [comment]
Hi @ilshm . Sorry for the late reply.

How about like this?

```ts
app.use(
  '/auth-verify-token/*',
  bearerAuth({
    verifyToken: async (token, c) => {
      if (token == dbQuery) {
        c.set('user', user)
        return true
      }
      return false
    }
  })
)

app.get('/auth-verify-token/page', (c) => {
  return c.json({ message: `Your user id is ${c.var.user.id}` })
})
```

**Comment by waynesbrain** [comment]
Some of the official middleware here returns a value and when I tried to copy from that middleware, I was going crazy trying to figure out how I can access that returned data.

Here is one place in [@hono/typebox-validator](https://github.com/honojs/middleware/blob/bebdfa2a8891435590bb941bd18c43e086458b02/packages/typebox-validator/src/index.ts#L93) ~ `return data`

and another in [@hono/zod-validator](https://github.com/honojs/middleware/blob/bebdfa2a8891435590bb941bd18c43e086458b02/packages/zod-validator/src/index.ts#L85) ~ `return result.data as z.infer<T>`

But meanwhile in the same middleware it will also do `return c.json(result, 400)`.

**Comment by waynesbrain** [comment]
Okay, I see that in those validators that I mentioned, the return value is actually available via `c.req.valid("json")` or `c.req.valid("query")` when I looked [here](https://github.com/honojs/hono/blob/16a9a949c66bd561e55fffba1580ddc18ef30857/src/validator/validator.ts#L147)
