### ISSUE TITLE
[zod-openapi]- running middleware after validation

### ISSUE THREAD

**Issue by ivandotv** [honojs/middleware#525]
I'm migrating the app from `Hono` to `OpenAPIHono` however I have stumbled upon a problem.

I have an `auth` middleware that runs before the final handler
```ts
export const usersRouter = new Hono()

usersRouter.post("/user-subscription", auth, userSubscription)
```
`auth` middleware is looking at the `request.headers` and it's deciding if it should proceed with the execution, it creates a `sesssion` for the downstream middleware to use.

The idea is that we check for the `headers`(needed for `auth`) via the validators in the `openAPI` spec, and if we have the correct headers then we run the `auth` middleware , and then the final handler.

 With `OpenAPIHono` this is not possible.
 
The problem with `OpenAPIHono` is that the middleware runs **before** the validators.
What is the reasoning behind that decision?

Ideally, we should run **validators** first , then run the middleware. If we can pass the `validation` stage then we know that we have a valid request.

Middleware that deals with business logic **before** validation is not usable.

**Comment by yusukebe** [comment]
Hi @ivandotv 

> What is the reasoning behind that decision?

This is to keep the implementation simple. If it allows multiple handlers, the type definition will be very, very complex.

Instead, you may use a Hook:

```tsapp.openapi(
  route,
  (c) => {
    const val = c.var.val
    return c.json()
  },
  (result, c) => {
    if (result.success) {
      c.set('val', 'foo')
      // auth
    }
  }
)
```

**Comment by ivandotv** [comment]
I believe breaking the middleware contract to have a type inference on the default handler is not worth it.
Open API can also have multiple responses, and putting that logic in one giant function will not work and will not scale.

Breaking the `middleware` contract (which is used in the original Hono, and other frameworks) is a bad decision

In the end I took the underlying [zod-to-openapi](https://github.com/asteasolutions/zod-to-openapi) package and did the implementation from scratch, respecting the middleware order.

Feel free to close this issue.

**Comment by yusukebe** [comment]
> Breaking the `middleware` contract (which is used in the original Hono, and other frameworks) is a bad decision

Regarding this "Zod OpenAPI Hono", our first idea is to implement OpenAPI with keeping the [RPC feature](https://hono.dev/guides/rpc). So we can't avoid that don't support multiple handlers.

> In the end I took the underlying [zod-to-openapi](https://github.com/asteasolutions/zod-to-openapi) package and did the implementation from scratch, respecting the middleware order.

It's a good idea. I think you don't need to use this Zod OpenAPI Hono.

Thanks. Closing the issue.
