### ISSUE TITLE
behind a reverse proxy, X-Forwarded-Proto isn't used and plain http is used for the signin action

### ISSUE THREAD

**Issue by bkerin** [honojs/middleware#537]
I'm running deno behind an apache2 (reverse proxy).  SSL is terminated at the apache2 and it uses plain http to communicate with the deno server.

The system I'm migrating from worked with: `RequestHeader set X-Forwarded-Proto "https"` but this middleware doesn't seem to notice this header, the /api/auth/signin page ends up containing:

```
<form action="http://betatest.mydomain.com/api/auth/signin/google" method="POST">
  <input type="hidden" name="csrfToken" value="8dc4c49dfe160f6a9737d67af01f22e42ba9e71adc7d55ebeecbd57c6076fb15">
  <input type="hidden" name="callbackUrl" value="http://betatest.mydomain.com">
```

I found that I could open the dev console and edit the element to just change that first http to https and then it submits without a warning.

I've got environment vars like so:

```
AUTH_TRUST_HOST=true
AUTH_URL=https://betatest.mydomain.com/api/auth/signin
```

But these apparently aren't enough to do it (the Auth.js docs seem to be saying the second one isn't needed).

Is there some way I'm missing to get https to be used here?

**Comment by beorn** [comment]
I found that although @auth/core supports trustHost (and rewrite the URL based on the headers), it seems @hono/auth-js also needs to do that a few places - otherwise the req.url that's used is wrong - e.g., getAuthUser(), reqWithEnvUrl().   You shouldn't have to set AUTH_URL - the default should work in most cases.  Even if you set AUTH_URL it doesn't work for some reason.

I found by wrapping the request with getXForwardedRequest (or fetch with behindProxy) as per https://jsr.io/@hongminhee/x-forwarded-fetch/0.2.0/mod.ts - it seems to work.

(A related problem is that Bun's websockets system isn't happy with wrapping app.fetch.)

**Comment by beorn** [comment]
Patching https://github.com/honojs/middleware/blob/main/packages/auth-js/src/index.ts to rewrite the request to take into account X-Forwarded-* headers as follows seems to do the trick:

## Patch getAuthUser
https://github.com/honojs/middleware/blob/39edec1249ec3f9dae474b1abc4ebc1cf97a51c2/packages/auth-js/src/index.ts#L69

```ts
  const origin = ctxEnv.AUTH_URL
    ? new URL(ctxEnv.AUTH_URL).origin
    : new URL((await getXForwardedRequest(c.req.raw)).url).origin // PATCH
```

## Patch authHandler

https://github.com/honojs/middleware/blob/39edec1249ec3f9dae474b1abc4ebc1cf97a51c2/packages/auth-js/src/index.ts#L130

```ts
    const req = await getXForwardedRequest(c.req.raw) // PATCH
    const res = await Auth(reqWithEnvUrl(req, ctxEnv.AUTH_URL), config) // PATCH
```

## getXForwardedRequest
using `getXForwardedRequest` from https://jsr.io/@hongminhee/x-forwarded-fetch/0.2.0/mod.ts#L24

```ts
/**
 * Returns a new {@link Request} object with `X-Forwarded-*` headers applied.
 * @param request A request object to be transformed.
 * @returns A new request object with `X-Forwarded-*` headers applied.
 */
export async function getXForwardedRequest(request: Request): Promise<Request> {
  const url = new URL(request.url)
  // console.log("rewriting req", request)
  const headers = new Headers(request.headers)
  const proto = request.headers.get("X-Forwarded-Proto")
  if (proto != null /*&& !proto.startsWith("ws")*/) {
    url.protocol = `${proto}:`
    headers.delete("X-Forwarded-Proto")
  }
  const host = request.headers.get("X-Forwarded-Host")
  if (host != null) {
    url.host = host
    const portMatch = host.match(/:(\d+)$/)
    if (portMatch) url.port = portMatch[1]
    else url.port = ""
    headers.delete("X-Forwarded-Host")
    headers.delete("Host")
    headers.set("Host", host)
  }
  return new Request(url, {
    method: request.method,
    headers,
    body:
      request.method === "GET" || request.method === "HEAD"
        ? undefined
        : await request.blob(),
    // @ts-ignore: TS2353
    referrer: "referrer" in request ? (request.referrer as string) : undefined,
    // deno-lint-ignore no-explicit-any
    referrerPolicy: request.referrerPolicy as any,
    mode: request.mode,
    credentials: request.credentials,
    // @ts-ignore: TS2353
    cache: request.cache,
    redirect: request.redirect,
    integrity: request.integrity,
    keepalive: request.keepalive,
    signal: request.signal
  })
}
```

**Comment by beorn** [comment]
@divyam234 Pls see above - not sure if it's possible to access the logic inside of @auth/core that presumably already does this (to support the trustHost functionality) instead of adding the getXForwardedRequest.

@yusukebe - Perhaps Hono (or Bun) could do this kind of rewriting too/instead?  Running behind a proxy/load-balancer is a common situation, and Express has a "trust proxy" setting that does this: https://expressjs.com/en/guide/behind-proxies.html

**Comment by beorn** [comment]
Unfortunately, `new Request()` does not copy over things like credentials so I get a CSRF error. That's why there's all the additional complexity in the `getXForwardedRequest()` function I guess.

**Comment by divyam234** [comment]
@beorn  Making new request from existing request only strips referrer field so it will not matter.

**Comment by beorn** [comment]
If I replace this block

https://github.com/honojs/middleware/blob/63898bbdabbf1d74dd4cc5bab96a670a8b203dae/packages/auth-js/src/index.ts#L49C1-L59C38

with this:

```ts
    return await getXForwardedRequest(req) // see above in issue for code
```

then it works (also need to make reqWithEnvUrl async of course).

**Comment by beorn** [comment]
Probably related to https://github.com/oven-sh/bun/issues/1381 - https://github.com/honojs/middleware/issues/81#issuecomment-1509457656 - this workaround seems to work:

Change:

https://github.com/honojs/middleware/blob/63898bbdabbf1d74dd4cc5bab96a670a8b203dae/packages/auth-js/src/index.ts#L59

to

```ts
return new Request(url.href, {
      headers: req.headers,
      method: req.method,
      body: req.method === "GET" || req.method === "HEAD" ? undefined : await req.blob()
})
```

Though I think it doesn't hurt to remove `x-forwarded-*` headers and update the `host` header.

**Comment by beorn** [comment]
FYI, this isn't fixed - see above

**Comment by ryanleecode** [comment]
This is still an issue

**Comment by ryanleecode** [comment]
> @divyam234 I've looked at it a bit more and the request.body isn't copied! it's probably related to [oven-sh/bun#1381](https://github.com/oven-sh/bun/issues/1381) - [#81 (comment)](https://github.com/honojs/middleware/issues/81#issuecomment-1509457656) - this workaround seems to work:
> 
> Change:
> 
> https://github.com/honojs/middleware/blob/63898bbdabbf1d74dd4cc5bab96a670a8b203dae/packages/auth-js/src/index.ts#L59
> 
> to
> 
> ```ts
> return new Request(url.href, {
>       headers: req.headers,
>       method: req.method,
>       body: req.method === "GET" || req.method === "HEAD" ? undefined : await req.blob()
> })
> ```
> 
> Though I think it doesn't hurt to also remove `x-forwarded-*` headers and update the `host` header.

Doing a pnpm patch with this fix worked

**Comment by catnaut** [comment]
I've reviewed the @auth/core implementation for the `/api/auth/signin` page. The render function in [`src/lib/pages/index.ts`](https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/lib/pages/index.ts#L84) uses the `signin` method to generate the form with a `callbackUrl` derived from `request.url.origin`. Consequently, setting the trusted host has no effect.

*(Additionally, this may indicate an issue within @auth/core itself: `params.callbackUrl ?? "/"` defaults to `/`, but `callbackUrl` has already been set as `request.url.origin`.)*

While [beorn’s](https://github.com/beorn) solution is technically correct, it introduces potential security risks. This approach could be vulnerable if users spoof the HTTP `X-Forwarded-For` header, which may lead to security issues. In my view, obtaining the actual request data should be managed through a transparent middleware, such  https://github.com/honojs/hono/issues/3646.

*By the way, Hono team are working on discussion the Proxy Helper for the proxy use case to avoid the user writing code for copying headers: https://github.com/honojs/hono/pull/3589*
