### ISSUE TITLE
Grouped Route Path Parameters Not Recognized in @hono/zod-openapi

### ISSUE THREAD

**Issue by HiraiKyo** [honojs/middleware#547]
**Issue description**:
I'm encountering a problem with the `hono/zod-openapi` package where path parameters are not recognized when they're used in a sub-application routing configuration. Here's a detailed description of the issue:

- @hono/zod-openapi: 0.12.1

**Not working (sub-application with parameterized route)**:
```javascript
const appGet = new Hono();
const route = createRoute({
  path: "/",
  method: "get",
  description: "test",
  request: {
    params: z.object({
      matchOngoingId: z.string(),
    }),
  },
  // ...
});

const app = new Hono();
app.route("/{matchOngoingId}/get", appGet); // Path parameter not captured, returns 404
```
In this configuration, the path parameter `matchOngoingId` does not get recognized and results in an error when trying to access the parameter in the sub-application.

**Working (direct application route with parameter)**:
```javascript
const appGet = new Hono();
const route = createRoute({
  path: "/{matchOngoingId}/get", // This works when directly placed here
  method: "get",
  description: "test",
  request: {
    params: z.object({
      matchOngoingId: z.string(),
    }),
  },
  // ...
});

const app = new Hono();
app.route("/", appGet);
```
Here, when the parameterized route is directly set in the main application, it works perfectly fine.

**Expected behavior**:
I would expect the path parameters to be captured regardless of whether they are defined in the main application or a sub-application.

**Actual behavior**:
The path parameters are not being captured when set via a sub-application.

It seems like a bug with routing in sub-applications. Could you please look into this?

Thank you!

**Comment by yusukebe** [comment]
Hi @HiraiKyo 

This is not a bug. The following format is not supported and we don't have a plan to implement it. Thanks.

```ts
app.route("/{matchOngoingId}/get", appGet)
```

**Comment by HiraiKyo** [comment]
Sorry for misunderstanding, this is the right way to implement path parameters.
```typescript
app.route("/:matchOngoingId/get", appGet)
```
Thanks for the reply!
