### ISSUE TITLE
Error with Hono, Swagger UI, and Zod OpenAPI Integration: Missing Parameter Data for Query Parameter with Refine and Transform

### ISSUE THREAD

**Issue by mandado** [honojs/middleware#560]
I encountered an issue with Hono, alongside the Swagger UI package and Zod OpenAPI.

The problem occurs when I pass a Zod schema to the query parameter of a request that contains a refine and a transform together.

It throws the following error and does not support typing.

Code: https://gist.github.com/mandado/420a0c72caae9438bf11fcca55815324

Response:
```json
{
  "message": "Missing parameter data, please specify `name` and other OpenAPI parameter props using the `param` field of `ZodSchema.openapi`",
  "data": {
    "missingField": "name",
    "location": "query",
    "route": "get /my-user"
  }
}
```

Type error: 

![image](https://github.com/honojs/middleware/assets/2823627/df7ad3ba-cbd4-4978-b827-8f210b59b105)
![image](https://github.com/honojs/middleware/assets/2823627/1d2d61d6-a935-4aa5-bdc6-6067c1f28643)

**Comment by yusukebe** [comment]
Hi @mandado 

In this case, you have to write the following to get it to work:

```ts
const test = createRoute({
  path: '/my-user',
  method: 'get',
  summary: 'Get a single user',
  request: {
    query: z.object({
      name: z
        .string()
        .optional()
        .refine(
          (name) => {
            return !name?.includes('forbidden')
          },
          {
            message: 'name is invalid'
          }
        )
    })
  },
  responses: {
    200: {
      description: 'Object with user data.',
      content: {
        'application/json': {
          schema: z.object({})
        }
      }
    },
    204: {
      description: 'No content - successful operation'
    }
  }
})
```

**Comment by mandado** [comment]
Hi @yusukebe, I don't understand the differences in the responses. What I know is that I can't use the "refine" and "transform" together because this breaks the app.

**Comment by mandado** [comment]
@yusukebe  version ^0.14.0

**Comment by yusukebe** [comment]
@mandado 

Thanks. Can you update it to `0.14.3`? and try the following code?

```ts
import { createRoute, OpenAPIHono, z } from '@hono/zod-openapi'

const app = new OpenAPIHono()

const test = createRoute({
  path: '/my-user',
  method: 'get',
  summary: 'Get a single user',
  request: {
    query: z // <--- Type Error
      .object({
        name: z.string().optional()
      })
      .refine(
        (data) => {
          return !data.name?.includes('forbidden')
        },
        {
          message: 'name is invalid'
        }
      )
      .transform((data) => {
        return data
      })
  },
  responses: {
    200: {
      description: 'Object with user data.',
      content: {
        'application/json': {
          schema: z.object({})
        }
      }
    },
    204: {
      description: 'No content - successful operation'
    }
  }
})

app.openapi(test, (c) => {
  const { name } = c.req.valid('query') // <--- Type Error
  return c.json({
    name,
    age: 20
  })
})

// ...
```

The error message will be the following:

```json
{"success":false,"error":{"issues":[{"code":"custom","message":"name is invalid","path":[]}],"name":"ZodError"}}
```

This may be what you expected.

But, it throws type errors yet. I think this is an issue related to https://github.com/asteasolutions/zod-to-openapi/issues/238

**Comment by mandado** [comment]
Yes! Works well! This is what I'm expecting thank you so much!.

**Comment by yusukebe** [comment]
Hey @mandado 

Can you try `@hono/zod-openapi@0.14.5`? which includes the new version of `@asteasolutions/zod-to-openapi`?
