### ISSUE TITLE
[BUG]: Zod OpenAPI RPC Mode not working with nullable query params

### ISSUE THREAD

**Issue by fellipeutaka** [honojs/middleware#562]
This is an example of a route using nullable query params:

```ts
export const getEventAttendees = new OpenAPIHono().openapi(
  createRoute({
    method: "get",
    path: "/:eventId/attendees",
    request: {
      params: z.object({
        eventId: z.string().uuid(),
      }),
      query: z.object({
        query: z.string().nullish().default(null),
        pageIndex: z
          .string()
          .nullish()
          .default("0")
          .transform(Number)
          .pipe(z.number().int().positive()),
      }),
    },
    responses: {
      ...
    },
  }),
  async (c) => {
    ...
  },
);
```

When I try to use the RPC Client, I get the following error:

``Property 'attendees' does not exist on type 'ClientRequest<{ [x: `$${Lowercase<string>}`]: { input: Partial<ValidationTargets>; output: any; outputFormat: string; status: StatusCode; }; }>'.``

```ts
api.events[":eventId"].attendees.$get({
    param: params,
    query: { query: q, pageIndex },
  });
```

Also, I get this weird type:
![image](https://github.com/honojs/middleware/assets/68625746/a7d865bb-8bea-4a24-b536-a8fa77202dee)

Removing `.nullish()` from `query` and `pageIndex`, the route type goes back to normal:
![image](https://github.com/honojs/middleware/assets/68625746/5a1c65aa-904b-48e5-beb4-f8adc723f06e)

I also tried to use `.nullable()` instead but the issue stills persists.

### Environment & setup

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11
Binaries:
  Node: 20.12.2
  pnpm: 9.2.0
Relevant Packages:
  @hono/zod-openapi: 0.14.2
  hono: 4.4.4
  typescript: 5.4.5
```

**Comment by fellipeutaka** [comment]
Also, I noticed that when you send `null` to query params, the value is getting transformed to a string, like `'null'` .

Sending null example:
```ts
api.events[":eventId"].attendees.$get({
    param: params,
    query: { query: q, pageIndex },
  });
```

**Comment by yusukebe** [comment]
Hi @fellipeutaka 

`query` can't accept `null`, so you can't use `.nulish()`. Instead, use `.optional()`.
