### ISSUE TITLE
[@hono/node-ws] ReferenceError: CloseEvent is not defined

### ISSUE THREAD

**Issue by Lorenzo0111** [honojs/middleware#595]
I'm using Node `v20.14.0` with @hono/node-ws `v1.0.1` and when listening to the onClose event it throws the following error:
```js
events.onClose?.(new CloseEvent("close"), ctx);
                     ^

ReferenceError: CloseEvent is not defined
```

**Comment by MrBazlow** [comment]
Spotted this as well with node.js `v22.3.0` although this seems to be an upstream issue which already has a committed fix. https://github.com/nodejs/node/pull/53355

My monkeycode patch for it right now is to just slot this in somewhere [using this for reference] (https://websockets.spec.whatwg.org/#closeevent)

```js
globalThis.CloseEvent = class CloseEvent extends Event {
  constructor(type, eventInitDict = {}) {
    super(type, eventInitDict);

    if (eventInitDict.wasClean) this.wasClean = eventInitDict.wasClean;
    if (eventInitDict.code) this.code = eventInitDict.code;
    if (eventInitDict.reason) this.reason = eventInitDict.reason;
  }

  wasClean = false;
  code = 0;
  reason = "";
};

```

**Comment by Lorenzo0111** [comment]
Well, on close doesn't really close and connections gets multiplied everytime. I guess the module is bugged
