### ISSUE TITLE
TS 2589: Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by directormac** [honojs/middleware#596]
This is related to [this](https://github.com/honojs/middleware/tree/main/packages/zod-openapi#a-dry-approach-to-handling-validation-errors) Where TS 2589 warning occurs.

```ts
app.openapi(
  createBookRoute,
  (c) => {
    const { title } = c.req.valid('json')
    return c.json({ title }, 200)
  },
  (result, c) => {
    if (!result.success) {
      return c.json(
        {
          ok: false,
          source: 'routeHook' as const,
        },
        400
      )
    }
  }
)
```

Where at the line where return c.json() the error occurs.

**Comment by cainenielsen** [comment]
I too am experiencing this and am not sure how to continue.
