### ISSUE TITLE
[@hono/node-ws] Duplicate Event Listeners in Middleware

### ISSUE THREAD

**Issue by totoraj930** [honojs/middleware#603]
In upgradeWebSocket, a 'connection' event listener is being set on `wss`. As the number of new connections increases, the event is called the same number of times.

https://github.com/honojs/middleware/blob/ec6ec4ec02f8db46e3151e7334535e562dfc47e3/packages/node-ws/src/index.ts#L45-L98

In `upgradeWebSocket`, only event listeners ('message', 'close', 'error') should be set on `ws`.

Initially, a new `wss` was created within `upgradeWebSocket`, so this issue did not occur. However, since `wss` is now reused, generated in `injectWebSocket`, this problem has arisen. (https://github.com/honojs/middleware/pull/539)

I attempted to fix the issue, but due to my shallow understanding of the middleware lifecycle, I couldn't succeed. Do you have any ideas?

@nakasyou @mikestopcontinues

**Comment by inaridiy** [comment]
I'll try to fix it a bit.

**Comment by inaridiy** [comment]
I fixed some things in the next PR. Maybe it will work.

https://github.com/honojs/middleware/pull/605

**Comment by yusukebe** [comment]
This was fixed by #605 thanks to @inaridiy !
