### ISSUE TITLE
reqWithEnvUrl report error: TypeError: Can't modify immutable headers

### ISSUE THREAD

**Issue by zhengrenzhe** [honojs/middleware#613]
hi @divyam234, i upgraded @hono/auth-js to 1.0.9, but encountered the error 'TypeError: Can't modify immutable headers' when got request, here is call stack:

<img width="943" alt="截屏2024-07-03 22 48 39" src="https://github.com/honojs/middleware/assets/5652241/3339156b-9448-40b5-ae7d-c5aa2ac6af6e">

The problem seems to originate from this [commit](https://github.com/honojs/middleware/commit/eb7e597aaabce2b2ac6e7809579c44f440c2b8b0#diff-47c3a626ec9512503fe75594bb5a8c58f32d8601c13e7ea021e2c98846db1e5eR86) 

i started hono from localhost(http), the http protocol is http1.1, chrome sends 'Host' in request header, so if-statement is triggered.
<img width="221" alt="截屏2024-07-03 22 57 37" src="https://github.com/honojs/middleware/assets/5652241/39427c91-852d-443c-9b4e-126fbe3ae68d">
<img width="436" alt="截屏2024-07-03 22 53 01" src="https://github.com/honojs/middleware/assets/5652241/db6c6284-2ca8-469d-b30d-289c8ab9c002">

However, in the online version using HTTPS and HTTP/2 protocol, chrome does not send 'Host' in request header, so hono does not crash, here is request headers:
<img width="219" alt="截屏2024-07-03 22 57 07" src="https://github.com/honojs/middleware/assets/5652241/9a1f8b96-5e5e-49a4-813f-d7ce88e59216">

so, this seems like a bug?

**Comment by divyam234** [comment]
@zhengrenzhe  raised a pr  for this   should be working from next build
