### ISSUE TITLE
Improve type definitions for arguments in `RootResolver` of graphql-server

### ISSUE THREAD

**Issue by 3w36zj6** [honojs/middleware#655]
The argument `c` in `RootResolver`, which represents `Context`, is defined as an optional property. However, I believe there is no need to consider it as `undefined`.
In the current implementation, it is necessary to check whether `c` is `undefined` before using it within `RootResolver`, which I find inconvenient.

https://github.com/honojs/middleware/blob/ab1b831e1a2dd311ce1752e0fa845761515e57fb/packages/graphql-server/src/index.ts#L23-L27

**Comment by yusukebe** [comment]
@3w36zj6 Thank you for the issue.

@metrue Could you take a look?

**Comment by metrue** [comment]
@yusukebe @3w36zj6  
PR is ready for review, please take a look https://github.com/honojs/middleware/pull/705
