### ISSUE TITLE
@hono/zod-validator - wronge type inference when the response is error

### ISSUE THREAD

**Issue by tomer-yechiel** [honojs/middleware#692]
```typescript
const res = await client.foo.$post()

if(res.status === 400){
   const data = await res.json(); // type of data should be SafeParseReturnType
}
```

**Comment by yusukebe** [comment]
Hi @tomer-yechiel 

Add the status number in `c.json()` explicitly: 

```ts
const routes = app.post('/', (c) => {
  if (error) {
    return c.json({ ok: false }, 400)
  }
  return c.json({ ok: true }, 200)
})
```

**Comment by tomer-yechiel** [comment]
Hi @yusukebe 
my route is the following
```typescript
const route = app.post('/', zValidator('json', schema), c => {...});
```

do you mean I need to use hook?

**Comment by yusukebe** [comment]
@tomer-yechiel 

Ah, I understand your problem. This is a known issue. Related to: 

https://github.com/honojs/middleware/issues/580
https://github.com/honojs/hono/issues/2719

We have to resolve this, but we don't have a good idea 😢
