### ISSUE TITLE
Typebox validator  hook not calling

### ISSUE THREAD

**Issue by Micnubinub** [honojs/middleware#727]
My hook isn't calling for some reason:

```ts
function parseValidationError(result, context) {
console.log({ result, context });
}

app.post('/endpoint',tbValidator(
  'json',
  t.Object({
    user: tNewUser,
    role: tCompanyRole,
    company: t.String()
  }), parseValidationError), async (c) => {
  ...
  return c.json({
    ...
  });
}
```
When I send invalid data to `/endpoint` I'm expecting it to log, am I doing something wrong? It's responding to the client with the `ValueError[]`
```json
"@hono/typebox-validator": "0.2.4",
"hono": "4.5.11",
```

**Comment by yusukebe** [comment]
HI @Micnubinub 

@curtislarson Can you take a look at this?

**Comment by Micnubinub** [comment]
Any update on this?

**Comment by yusukebe** [comment]
@Micnubinub 

I've tried it but I can't reproduce it. If you want my help, please provide a minimal project to reproduce it.

**Comment by Micnubinub** [comment]
We can close this one... It's the one I made a pull request for last time

**Comment by Micnubinub** [comment]
We can close this one... It's the one I made a pull request for last time

**Comment by yusukebe** [comment]
@Micnubinub 

Ah, okay!
