### ISSUE TITLE
zValidator parsing url queries containing nested object

### ISSUE THREAD

**Issue by believelody** [honojs/middleware#737]
Hi guys,
Wondering how to validate (and design schema) a route with zValidator with an url like this : http://hostname/products/paginate?limit=8&filters[productName]=fr.

My issue is **filters** which is a nested object. This is what I did:
```
zValidator("query", z.object({
    limit: z.string().optional(),
    filters: z.object({
        productName: z.string().optional()
    }).optional()
}))
```

When retrieving my query value with `ctx.req.valid("query")`, **filters** is missing.
I'm pretty sure it's mostly related to zod itself, but how to design the schema and get an object as :
```
{
    limit?: string;
    filters?: {
        productName?: string;
    }
}
```

**Comment by mhio** [comment]
In a URL, that would normally parse as a key of `filters[productName]` = `fr`.

I believe the only complex data structure hono supports for query params is building an array out repeated names.

**Comment by believelody** [comment]
> In a URL, that would normally parse as a query param named `filters[productName]` with a value of `fr`.
> 
> I believe the only complex data structure hono supports for query params is building an array out repeated names.

I thought that it would be parsed as expected. I decided to juste use a first level queries !
Thank you for your reply.

**Comment by yusukebe** [comment]
Hi @believelody !

Can we close this issue?

**Comment by believelody** [comment]
Hi @yusukebe , I was hoping that someone gives me / suggests a proper solution. I close it.

**Comment by paulwongx** [comment]
I'm having this same issue. It seems to be calling `String()` on query params passed in but it should be serialized properly. I believe this is a bug...

**Comment by paulwongx** [comment]
Had a discussion on Discord about this.

Link: https://discord.com/channels/1011308539819597844/1222281743948845239/threads/1370139490139635783

I think overall, this is typically not provided out of the box apparently and URLSearchParams also doesn't support this so as per OP, I think we just have to make it flat.

**Comment by mhio** [comment]
@paulwongx What schema does the `qs` module implement? What browsers/libraries/clients serialize query params to that format?

For using a complex data structure in existing Hono, and the values really have to be transferred via query params, I'd suggest putting the serialized string all in one param and having zod [preprocess](https://zod.dev/?id=preprocess) that value into a schema. Something like:

```
const schema_the_vals = z.object({
     sval: z.string(),
     aval: z.array(z.string),
})
const schema_the_vals_in = z.preprocess((str) => anyURISafeDeserializer(str), schema_the_vals)
const schema_the_vals_out = schema_the_vals.transform((obj) => anyURISafeSerializer(obj))
zValidator("query", z.object({
    qs: schema_the_vals_in
}))

client({ query: { qs: schema_the_vals_out.parse(val) } })
```

That doesn't fix the hc client types but does validate both ends.

**Comment by prpanto** [comment]
I was late to the party but I find a good solution for parsing the query to beautiful object. I use `qs` lib to convert this kind of queries and I use the decoder for extra changes, See my example above.

```js
import { z } from "zod";
import qs from "qs";

const query = "?filter[color]=red&filter[size]=large&user[post][id]=385&sort=-createdAt&include=author,comments&active=true";

const queryObject = qs.parse(query, {
  ignoreQueryPrefix: true,
  decoder: (str: string, defaultDecoder: qs.defaultDecoder, charset: string, type: "key" | "value") => {    
    if (type === "value" && !!Number(str)) {
      return Number(str);
    }

    if (type === "value" && str === "true") {
      return true;
    }
    
    if (type === "value" && str === "false") {
      return false;
    }

    if (type === "value" && str.includes(",")) {
      return str.split(",").map((s: string) => s.trim());
    }

    return defaultDecoder(str);
  }
});

console.log(queryObject);

const querySchema = z.object({
  filter: z.object({
    color: z.string().optional(),
    size: z.string().optional(),
  }).optional(),
  user: z.object({
    post: z.object({
      id: z.int().optional(),
    }).optional(),
  }).optional(),
  sort: z.string().optional(),
  include: z.array(z.string()).optional(),
  active: z.boolean().optional(),
});

const result = querySchema.parse(queryObject);
```
