### ISSUE TITLE
Denoify to DNT

### ISSUE THREAD

**Issue by un-focused** [honojs/middleware#76]
Hi! I was planning on making my own framework as I found most frameworks having issues with edge environments & this framework is awesome so far! So first of all great work!!

As I started looking at the packages, I realized that denoify was being used to convert the package from an npm module to a deno module. Deno has an official package that does the opposite & seems to have better support, you can find it [here](https://github.com/denoland/dnt).

I was wondering if it would make sense to reverse it to go from Deno to NPM instead of NPM to Deno?

**Comment by yusukebe** [comment]
Hi @un-focused !

Thanks for saying so! Please try to use it!

You are right, we could use `DNT`. However, we continue to use `denoify` for several reasons.

* We are using Cloudflare Workers implementation as a reference implementation.
* We would like to run the main tests in the miniflare environment.
* While Deno is good, npm-based modules are easier for everyone to contribute to.
* As of now, there are no issues with `denoify`.

Indeed, DNT is also a good option.

**Comment by un-focused** [comment]
Thank you for the clarification! I am having some issues with the typescript types in Deno & I thought it might be due to Denoify. I will investigate it further before making an issue.

Thank you for all the work!

**Comment by yusukebe** [comment]
I'll closing this now. If you have the problem, feel free to reopen. Thanks!
