### ISSUE TITLE
`@cloudflare/workers-types` and `@hono/zod-openapi` seems to not play nice with each other

### ISSUE THREAD

**Issue by thisjt** [honojs/middleware#781]
I have this issue of `@cloudflare/workers-types` messing up with the types that `@hono/zod-openapi` currently emits.

![image](https://github.com/user-attachments/assets/80a5e1ff-d807-4035-8d1a-1e28a499a80f)
![image](https://github.com/user-attachments/assets/4fe074db-a0f8-44f0-b017-3d7711ab2d82)

Minimum reproducible code would be to do `pnpm create hono@latest`, pick cloudflare workers, then follow this tutorial from [Zod OpenAPI](https://hono.dev/examples/zod-openapi) middleware.

The issue gets fixed when I do `pnpm remove @cloudflare/workers-types`, which could potentially be a cloudflare worker types issue.

**Comment by thisjt** [comment]
Potentially related to this issue:

https://github.com/honojs/hono/issues/1547

**Comment by yusukebe** [comment]
Hi @thisjt 

I can't reproduce it. If you want a help, please provide a minimal project to reproduce it.

![CleanShot 2024-10-16 at 18 09 14@2x](https://github.com/user-attachments/assets/5cfcd8a3-90e4-4a1f-b4f4-952efcca8813)

**Comment by thisjt** [comment]
Thanks for checking. I narrowed down the issue, and it seems like the response codes does not go well with using the `http-status-codes` library due to `StatusCodes.OK` being an `enum` instead of a `const`. My bad. I'll close this now.

```ts
const OK = 200;

const route = createRoute({
  method: 'get',
  path: '/users/{id}',
  request: {
    params: ParamsSchema,
  },
  responses: {
    // StatusCodes.OK is an enum, replacing this with `[OK]` solved the problem
    [StatusCodes.OK]: {
      content: {
        'application/json': {
          schema: UserSchema,
        },
      },
      description: 'Retrieve the user',
    },
  },
});
```

I'm now using `stoker/http-status-phrases` as my http status code library.
