### ISSUE TITLE
Zod validator doesn't transform the types correctly

### ISSUE THREAD

**Issue by ceifa** [honojs/middleware#782]
When using zod, I expect to use the return type of the parse inside my route, but today the `param` function it's fixed on string return:

```js
.put(
    '/:id',
    zValidator('param', z.object({ id: z.coerce.number() })),
    async ctx => {
        const id = ctx.req.param('id') // string
}
```

**Comment by yusukebe** [comment]
Hi @ceifa 

Use `ctx.req.valid()`:

```ts
const { id } = ctx.req.valid('param')
```

**Comment by ceifa** [comment]
Great to know that there is an API for that!

Although, I don’t think it is intuitive, would be great to have it implemented on param function.

**Comment by ceifa** [comment]
The same doesn't work for queries:

![image](https://github.com/user-attachments/assets/6f583aed-e28d-4256-8d9e-566483a61b55)

Am I missing something or hono have limitations with zod? @yusukebe

**Comment by yusukebe** [comment]
@ceifa 

Please provide the code to reproduce it.
