### ISSUE TITLE
[zod-openapi] c.req.valid in middleware returns undefined

### ISSUE THREAD

**Issue by MrSquaare** [honojs/middleware#787]
Hi,

I'm trying to create a middleware that will retrieve the headers according to how they were described by the zod schema.
So I'm using `c.req.valid("header")`.
However, this method returns undefined in the middleware, where it would return the correct values in the handler.

Here's some reproduction code: 

```ts
import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";
import { Env } from "hono";
import { createMiddleware } from "hono/factory";

type MyCustomInput = {
  out: {
    header: {
      authorization: string;
    };
  };
};

const myMiddleware = createMiddleware<Env, string, MyCustomInput>((c, next) => {
  const headers = c.req.valid("header");

  console.log("My headers", headers);

  return next();
});

const myDemoApp = new OpenAPIHono().openapi(
  createRoute({
    method: "get",
    path: "/",
    middleware: [myMiddleware],
    request: {
      headers: z.object({
        authorization: z.string(),
      }),
    },
    responses: {
      200: {
        description: "Success",
        content: {
          "text/plain": {
            schema: z.string(),
          },
        },
      },
    },
  }),
  (c) => {
    const headers = c.req.valid("header");

    console.log("My headers", headers);

    return c.text("Hello, world!");
  },
);
```

Output:
```
My headers undefined
My headers { authorization: 'Bearer SECRET' }
```

**Comment by MrSquaare** [comment]
This seems expected: https://github.com/honojs/middleware/blob/2d1a89df26f2ec42e1dc0e5845cf691bdcbe23e2/packages/zod-openapi/src/index.ts#L440

**Comment by yusukebe** [comment]
Hi @MrSquaare 

Hmmmm. As you pointed out, the middleware is executed before validators. How about using Combine Middleware, though I don't know if it resolves this problem?

https://hono.dev/docs/middleware/builtin/combine

**Comment by MrSquaare** [comment]
Hello @yusukebe

Thanks for your reply!

I forgot to give an update regarding this ticket, but this is indeed the solution I integrated.

Moreover, I find it more robust than admitting that the schema will always be defined in the OpenAPI specification.

I'll close this ticket since my problem is resolved, thanks again
