### ISSUE TITLE
Malformed JSON in request body

### ISSUE THREAD

**Issue by adityabrahmankar** [honojs/middleware#799]
Hey !

- Tech stack is Next 15 react19rc
- @tanstack/react-query
- and Hono RPC 
- with bun as package manager

I am using zValidator middleware and even after passing the headers for content-type as application/json I am getting the error Malformed JSON in request body. Also the image shows the content-type as plain-text 👇

![image](https://github.com/user-attachments/assets/d1698303-fc50-4c7c-9863-5bf28131bcc9)

```
// use-create-workspace.ts

import { client } from "@/lib/rpc";

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { InferRequestType, InferResponseType } from "hono";
import { useRouter } from "next/navigation";

type ResponseType = InferResponseType<typeof client.api.workspaces["$post"], 200>
type RequestType = InferRequestType<typeof client.api.workspaces["$post"]>["json"]

export const useCreateWorkspace = () => {
  const queryClient = useQueryClient()
  const router = useRouter()

  const mutation = useMutation<
    ResponseType,
    Error,
    RequestType
  >({
    mutationFn: async (json) => {
      const response = await client.api.workspaces.$post({
        json
      },{
        headers: {
          "Content-Type": "application/json"
        }
      })

      if (!response.ok) {
        throw new Error("Something went wrong");
      }

      return await response.json()
    },
    onSuccess() {
      router.refresh()
      queryClient.invalidateQueries({ queryKey: ["workspaces"] })
    },
  })

  return mutation
}
```

```
// mutate function

  const onSubmit = async (values: z.infer<typeof createWorkspaceSchema>) => {

    mutate({
      name: values.name
    }, {
      onSuccess() {
        toast.success(` Workspace created successfully`)
      }
    })
```

```
.post(
    "/",
    verifyAuth(),
    zValidator(
      "json",
      z.object({
        name: z.string().min(1).max(20)
      }),
    ),
    async (c) => {
      const auth = c.get("authUser")
      const { name } = c.req.valid("json")
      
      if (!auth.token?.id) {
        return c.json({ error: "Unauthorized" }, 401)
      }
      
      ...somedata
      
      return c.json({
        some data
      })
    }
  )
  ```

**Comment by 985563349** [comment]
I had the same problem.

**Comment by yusukebe** [comment]
Hi @adityabrahmankar @985563349 

Please share a ***minimal*** project to reproduce it.

**Comment by adityabrahmankar** [comment]
Tried again no issue this time !!

**Comment by 985563349** [comment]
@yusukebe 
I found that calling await c.req.json() throws Malformed JSON in request body after using verifyAuth middleware. sorry, this example is a bit complicated and I don't know how to organize it yet.

**Comment by BakauDesign** [comment]
This validator will create "Malformed JSON in request body" problem

`import type { Context } from 'hono';
import { validator } from 'hono/validator';

interface Customer {
    id: number;
    userId: number;
    name: string;
    avatar: string;
}

export class CustomerValidator {
    private async validateCommon(value: Customer, c: Context) {
        const errors: { [key: string]: string } = {};

        if (!value.userId) {
            errors.userId = "userId cannot be empty";
        }

        if (!value.name) {
            errors.name = "name cannot be empty";
        }

        if (!value.avatar) {
            errors.avatar = "avatar cannot be empty";
        }

        return errors;
    }

    validateCreate() {
        return validator('json', async (value: Customer, c) => {
            const errors = await this.validateCommon(value, c);

            const userId = c.req.param()

            console.info(userId)

            if (Object.keys(errors).length > 0) {
                return c.json({
                    errors: errors
                }, 403);
            }
        });
    }

    // validateGetById() {
    //     return validator('param', (value: Customer, c) => {
    //         const errors = this.validateCommon(value, c);

    //         if (!value.id) {
    //             errors.id = "id cannot be empty";
    //         }

    //         if (Object.keys(errors).length > 0) {
    //             return c.json({
    //                 errors: errors
    //             }, 403);
    //         }
    //     });
    // }

    validateUpdate() {
        return validator('json', (value: Customer, c) => {
            const errors = this.validateCommon(value, c);

            // if (!value.id) {
            //     errors.id = "id cannot be empty";
            // }

            if (Object.keys(errors).length > 0) {
                return c.json({
                    errors: errors
                }, 403);
            }
        });
    }

    validateDelete() {
        return validator('json', (value: Customer, c) => {
            const errors = this.validateCommon(value, c);

            // if (!value.id) {
            //     errors.id = "id cannot be empty";
            // }

            if (Object.keys(errors).length > 0) {
                return c.json({
                    errors: errors
                }, 403);
            }
        });
    }
}`
