### ISSUE TITLE
[zod-openapi] Middleware type inference issue with more than 1 middleware

### ISSUE THREAD

**Issue by askorupskyy** [honojs/middleware#847]
After the type inference has been added in [@hono/zod-openapi@0.17.1](https://github.com/honojs/middleware/releases/tag/%40hono%2Fzod-openapi%400.17.1) (thanks a lot), I've encountered an issue with my middleware context after having multiple middlewares:

Here's my middleware for the route:

```typescript
const update = createRoute({
  middleware: [useAuth, useAccess(['ADMIN', 'CLINIC'])] as const,
});
```

`useAuth` writes the following type into the context (`c.var.user`):

```typescript
type SessionUser = {
    name: string | null;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    accessFlags: string[];
    ....
}
```

The type error is thrown when I try to access the `createdAt` or `updatedAt` fields:
Since both fields are being casted to this:

```typescript
createdAt: {
  toString: {};
  toDateString: {};
  toTimeString: {};
  toLocaleString: {};
  toLocaleDateString: {};
  toLocaleTimeString: {};
  valueOf: {};
  getTime: {};
  getFullYear: {};
   ... 34 more ...;
  [Symbol.toPrimitive]: {};
};
```

- I verified there's nothing wrong with the middleware itself. 
- The issue happens if I have more than 1 middleware in the route. This can be _any_ middleware, even if I duplicate my `useAuth` the issue persists.

**Comment by vinicius507** [comment]
Something similar happening here when passing multiple handlers to the middleware field.

Executing `c.get('resolve')(Token)` (from `@hono/tsyringe`) with multiple middlewares, but tsserver thinks `c.get('resolve')` resolves to `never`:

```
├╴ This expression is not callable.
│     Type 'never' has no call signatures. ts (2349) [8, 19]
```

**Comment by sushichan044** [comment]
@yusukebe Hi, I'm currently working on this issue.
Perhaps the problem is that this DeepSimplify type branching is done with `extends object`.
https://github.com/honojs/middleware/blob/83cc76469e270bbc71bc632e0ef945f7f5554ba3/packages/zod-openapi/src/index.ts#L219-L225

How about changing this to `Record<string, unknown>` and so on?

**Comment by askorupskyy** [comment]
@sushichan044 yup i just removed `DeepSimplify` and it works. Making a PR to remove it rn?

**Comment by askorupskyy** [comment]
Not really sure `DeepSimplify` is needed there. Why would we need a simplified `env` by default?

**Comment by sushichan044** [comment]
Certainly, there is no such processing in the `HandlerInterface` or `CreateHandlersInterface` . 
It might be better to align the behavior.

**Comment by askorupskyy** [comment]
Nvm removing `DeepSimplify` breaks some tests. Apparently it prevents this behavior:

```typescript
type Env = {
  Variables: { foo: string }
} & { Variables: { bar: string }
```

You were right about making it a `Record<string, unknown>`.

I am making a pr now...

**Comment by sushichan044** [comment]
@askorupskyy 
This test is written assuming `DeepSimplify`, 
so if we prefer not to use this type, you will need to change the test as well.

**Comment by sushichan044** [comment]
@askorupskyy 
This test is written assuming `DeepSimplify`, 
so if we prefer not to use this type, we will need to change the test as well.
https://github.com/honojs/middleware/blob/83cc76469e270bbc71bc632e0ef945f7f5554ba3/packages/zod-openapi/test/index.test-d.ts#L251-L277

**Comment by askorupskyy** [comment]
I made it work without breaking that test. Thanks @sushichan044 I really appreciate your input on this. `DeepSimplify` _is_, in fact, needed. Would've taken me a while to realize this `Record<string, unknown>` thing....

**Comment by askorupskyy** [comment]
The fix is out and I've already tested in my repo @vinicius507. Update to latest package version.

**Comment by vinicius507** [comment]
I updated to the latest version of `@hono/zod-openapi` and the issue reamains.

<img width="1218" alt="image" src="https://github.com/user-attachments/assets/b3f6a0c0-f84a-4050-ba33-2885194684f4" />


Route:

```ts
export const createInvite = createRoute({
  summary: "Create Invite",
  description: "Creates an user invite.",
  method: "post",
  path: "/",
  tags,
  middleware: [jwt(), serializeResponse(201, ReadInviteSchema)],
  request: {
    body: {
      content: {
        "application/json": {
          schema: CreateInviteSchema,
        },
      },
    },
  },
  responses: {
    201: {
      description: "Successfully created user invite.",
      content: {
        "application/json": {
          schema: ReadInviteSchema,
        },
      },
    },
  },
});
```

Handler:

```ts
app.openapi(routes.createInvite, async (c) => {
  const service = c.get("resolve")(InvitesService);
  const { email, expiresAt } = c.req.valid("json");

  const invite = await service.create({ email, expiresAt });

  return c.json(invite, 201);
});
```

**Comment by askorupskyy** [comment]
@vinicius507 middleware: [] as const

this will make sure the array is static and types are inferred as-is

**Comment by vinicius507** [comment]
Thank you sir :) @askorupskyy

**Comment by mrlubos** [comment]
Can confirm `as const` is the trick for arrays, but had to come here to find out!

**Comment by cruatta** [comment]
> [@vinicius507](https://github.com/vinicius507) middleware: [] as const
> 
> this will make sure the array is read-only and types are inferred as-is

This absolutely needs to be in the docs. I'm glad I found this solution here
