### ISSUE TITLE
[zod-openapi] tests fail

### ISSUE THREAD

**Issue by valerii15298** [honojs/middleware#882]
I cloned this repo and tried to run tests in `zod-openapi` package.
Two tests have failed.

To reproduce:
```bash
git clone https://github.com/honojs/middleware.git
cd middleware/packages/zod-openapi
yarn install
yarn test
```

Yarn version:
```
❯ yarn -v
4.0.2
```

Node.js version:
```
❯ node -v
v22.3.0
```

Failed tests output:
```
 FAIL  test/index.test.ts > JSON and Form > functionInJSON should not be called when the body is Form
AssertionError: expected "spy" to be called at least once
 ❯ test/index.test.ts:772:28
    770|       body: form,
    771|     })
    772|     expect(functionInForm).toHaveBeenCalled()
       |                            ^
    773|     expect(functionInJSON).not.toHaveBeenCalled()
    774|     functionInForm.mockReset()

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed | 1 passed (2)
      Tests  1 failed | 51 passed (52)
   Start at  17:18:52
   Duration  222ms (transform 45ms, setup 0ms, collect 98ms, tests 34ms, environment 0ms, prepare 52ms)
```

Screenshots:
<img width="1367" alt="Screenshot 2024-12-11 at 17 22 29" src="https://github.com/user-attachments/assets/02f368fd-bc38-48c8-8c5f-716f96f71f4f" />

<img width="465" alt="Screenshot 2024-12-11 at 17 22 47" src="https://github.com/user-attachments/assets/aec5c624-293b-42cb-a18e-efe9f3f12c19" />

**Comment by askorupskyy** [comment]
```
 Test Files  4 passed (4)
      Tests  66 passed (66)
Type Errors  no errors
```

Lol? This repo has a test runner for every PR and merge to `main`. If there was an issue with the tests – package would not be deployed.

**Comment by valerii15298** [comment]
I recorded a 40 seconds video of failing tests reproduction: https://youtu.be/bF_AoNyZd0Y
