### ISSUE TITLE
Resolve issue with 'Bearer SECRET, Bearer YOUR_SECRET_TOKEN'

### ISSUE THREAD

**Issue by akins-dev** [honojs/middleware#884]
```
const HeadersSchema = z.object({
  // Header keys must be in lowercase, `Authorization` is not allowed.
  authorization: z.string().openapi({
    example: 'Bearer SECRET',
  }),
})
```

The above gives me this :
```
{Authorization: 'Bearer SECRET, Bearer YOUR_SECRET_TOKEN'}
```

I guess it is being handled by default. So, I had to replace it with
`authorization: z.string().optional()`

Now it works fine and shows `{Authorization: 'Bearer YOUR_SECRET_TOKEN'}`

**I suggest fixing this in the docs to help others avoid this issue.**

**Comment by askorupskyy** [comment]
@akins-dev there's an open PR for this https://github.com/honojs/middleware/pull/860. Feel free to drop any suggestions there.

**Comment by yusukebe** [comment]
This can be fixed by https://github.com/honojs/middleware/pull/860 thanks to @askorupskyy . I'll close this now, if you have still any problem, please add a comment.
