### ISSUE TITLE
How do i write zod schema for the followings see comment 

### ISSUE THREAD

**Issue by adeel-m-dev** [honojs/middleware#92]
Hi everyone,

https://test@test.com/?page=1&limit=15&list=1%2C2%2C3
new URLSearchParams({page: 1, limit: 15, list: [1, 2, 3]}).toString()

import { Hono } from 'hono';
import { z } from 'zod';
import { zValidator } from '@hono/zod-validator';

const app = new Hono<{ Bindings: { aaa: string } }>().basePath('/api');

const schema = /???/ 
	

app.get('/post', zValidator('query', schema), async (c) => {
	const query=c.req.query('query')
	
	return c.json({ docs:[]});
});

i need to know how to write zod schema for this query

**Comment by yusukebe** [comment]
Hi @adeel-m-dev ,

Try this:

```ts
const app = new Hono<{ Bindings: { aaa: string } }>().basePath('/api')

const schema = z.object({
  page: z.string(),
  limit: z.string(),
  list: z.array(z.string()),
})

const route = app.get('/post', zValidator('query', schema), async (c) => {
  const query = c.req.valid('query')
  return c.jsonT({ query })
})
```
