### ISSUE TITLE
Using Zvalidator Middleware breaks Client types

### ISSUE THREAD

**Issue by paul1995tu** [honojs/middleware#93]
Hi, I am currently using hono with nodejs 18. When I create a Client for example 
```
export const Client = hc<typeof myRouter>(
    "http://localhost:8999/api",
    {
        headers: {
            "X-User-Agent": "hc",
            "Accept-Encoding": "gzip, deflate, br",
            Accept: "application/json",
            "Content-Type": "application/json",
            Authorization: "",
        },
    },
);
```

And a route uses the zValidator Middleware. I get type errors when I want to add headers to the Request, for example:

```
 await  Client.someData.$get({
        query: {
            data: data,
        },
        headers: {
            Authorization: `Bearer JWT`,
        },
    });
```

I get  <html>TS2345: Argument of type '{ query: { data: data; }; headers: { Authorization: string; }; }' is not assignable to parameter of type '{ query: { data: data; }; }'.<br/>Object literal may only specify known properties, and 'headers' does not exist in type '{ query: { data: data; }; }'.

**Comment by yusukebe** [comment]
@paul1995tu 

You should like the following:

```ts
await Client.someData.$get(
  {
    query: {
      data: data,
    },
  },
  {
    headers: {
      Authorization: 'Bearer JWT',
    },
  }
)
```

**Comment by paul1995tu** [comment]
thanks :)
