### ISSUE TITLE
[Propose] Server-Timing API

### ISSUE THREAD

**Issue by PassiDel** [honojs/middleware#99]
Moin!
First of all, thank you so much for developing Hono! I love it and can't ever go back to other frameworks.

In the past, I have included the [Server-Timing API](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing) everywhere I could. It helps me a lot, especially in production systems, to be able to keep track of individual durations.

To be able to use this functionality in hono, I wrote the [middleware and functions](https://github.com/PassiDel/hono-timing) for it. Now I wanted to ask if it is wanted to add this to the third-party or even to core.

The usage looks something like this:

```ts
import { serve } from '@hono/node-server';
import { Hono } from 'hono';
import { endTime, setMetric, startTime, timing } from "@puazzi/hono-timing";

const app = new Hono();

// add the middleware to your router
app.use('*', timing());

app.get('/', async (c) => {

  // add custom metrics
  setMetric(c, 'region', 'europe-west3')

  // add custom metrics with timing, must be in milliseconds
  setMetric(c, 'custom', 23.8, 'My custom Metric')

  // start a new timer
  startTime(c, 'db');
  const data = await db.findMany(...);

  // end the timer
  endTime(c, 'db');

  return c.json({ response: data });
});

serve(app);

```

![image](https://github.com/honojs/middleware/assets/22080311/fec047ee-f1f3-43b2-be41-af33449209a2)

Best regards from Germany!

**Comment by yusukebe** [comment]
Hi @PassiDel !

Thanks for creating the issue and this is awesome idea! I'd like to make it as a built-in middleware which means it's in the core package. It will be useful for measuring the performance and it's great that it does not depend on any other libraries.

I took a look at [your repository](https://github.com/PassiDel/hono-timing) and noticed that you are currently using `process.hrtime`. Unfortunately, this would not work in environments outside Node.js, such as Cloudflare Workers. Therefore, how about using `performance.now()` instead? This function is available in other runtimes, including Cloudflare Workers, and it provides high-resolution time stamps.

If you agree with integrating this as a built-in middleware, could you please open another issue or pull request in [the main repository](https://github.com/honojs/hono)?

Thanks from Japan!

**Comment by PassiDel** [comment]
Thank you! I would love to see this in the core package!

`performance.now()` indeed would be a better choice, for microsecond accuracy. I'll change that!

**Comment by yusukebe** [comment]
Closed!
